### ISSUE TITLE
stuck in creating conda enviroment

### ISSUE THREAD

**Issue by Dale12138** [loosolab/TOBIAS#102]
Hi!
Thanks for providing TOBIAS! I just encountered a conda issue when I tried out your snakemake pipeline version.
There are no any error messages. The screen printouts stop at : 
"Building DAG of jobs...
Creating conda environment environments/tools.yaml...
Downloading and installing remote packages.
"
I have waited a day for the job to proceed, but nothing gets updated while I can see the job is still running background.
Do you by any chance know what might cause this? Any guide would be much appreciated!!
Cheers,
Dale

**Comment by msbentsen** [comment]
Hi Dale,

This is unfortunately a known issue with Conda, not only for the TOBIAS snakemake pipeline...  but some things you might try are:
- In newer snakemake versions, you have the option to set `--conda-frontend mamba`, which forces snakemake to use the `mamba` package manager instead of conda, which is generally faster.
- Running `conda clean --all` has sometimes solved some of my issues with dependencies.
- If you can manage, you can also install the individual TOBIAS dependencies into one environment / on your path, and run the pipeline without `--use-conda`. The main tools needed are:
    - TOBIAS
    - MACS2
    - bedtools
    - pysam
    - uropa
    - ucsc-bedgraphtobigwig
    - pyfaidx
    - intervene
 
Although you might have to run it to check that all dependencies are found. In case you get errors in a non-essential rule, such as the rules for building wilson-files, you can set `--keep-going` for snakemake to continue running other rules regardless of  previous errors.

I hope any of these can help you out!

BR Mette

**Comment by Dale12138** [comment]
Hi Mette,
I really appreciate your suggestions here! I managed to use the original conda to run the pipeline by better organizing all input files and giving more resources. Just for some feedbacks, I also tried mamba, but failed, because the snakemake pipeline would skip creating sub conda environments under environments folder, which is essential for the pipeline to work. Probably mamba can work if there is a way to force mamba to run all sub environments; Otherwise, conda is the only solution.
Thanks again for all the help!
Cheers,
Dale
