### ISSUE TITLE
Help understanding atacorrect calculation of post-bias variance

### ISSUE THREAD

**Issue by HillJamie** [loosolab/TOBIAS#104]
Hi Mette

I have been puzzled by how negative counts are handled in the calculation of post-bias variances and was hoping you could help. The code is very simple:

`      
        	#Invert negative counts
		abssum = np.abs(np.sum(post_bias[strand].neg_counts, axis=0))
		post_bias[strand].neg_counts = post_bias[strand].neg_counts + abssum
		
		#Join negative/positive counts
		post_bias[strand].counts += post_bias[strand].neg_counts	#now pos

		post_bias[strand].prepare_mat()
`

As I understand it, negative counts occur when we observe fewer counts of a given nucleotide at a particular position than is expected based on the bias. Presumably one approach would be to round these up to zero i.e. not try to invert the counts at all. Instead the code adds a number of positive counts.

My confusion is best illustrated by this synthetic example 

![negCounts](https://user-images.githubusercontent.com/48618790/143878793-9f19c169-4fa8-433b-90af-7e27055725ca.png)

It is synthetic because the actual negative counts are probably small fractions of a count. Nevertheless, I interpret this to mean that, at the 4th position of a k-mer of length 10, a total of 8 negative counts are to be corrected for by adding 8 + 5 + 8 + 3 + 8 = 32 positive counts. Similarly, at the 8th position, a total of 7 negative counts are to be corrected for by adding 28 positive counts.

Is there a way of getting an intuition for why this procedure works, and whether it is preferable to rounding negative counts to zero? It seems, naively, that the negative counts have a disproportionate weighting, which might affect the subsequent calculation of the variance.

Thank you in advance for your time, and for TOBIAS,
Jamie

**Comment by msbentsen** [comment]
Hi Jaime,

Thank you for your question! It is a while since I wrote the code, so I just had to recall my own thoughts on that - I will try to explain the reasoning here:

You are absolutely right that negative counts occur when we observe fewer counts than expected, so technically, everything negative could be cut at 0. I believe I also played with this during development of the tool, but one issue with that is, that you lose the information whether the ATAC bias was over-corrected or wrongly corrected. That could happen if the wrong bias motif was calculated, thus ATACorrect would think that certain positions should have been high-signal -> but they are actually low signal -> which ends up pushing the corrected cut below 0 (less than expected). So for that reason, I kept the negative counts, in order to catch this effect.

But with that choice came another problem: The bias is treated like a sequence motif, and sequence motifs are not allowed to have negative 'counts'. So in order to establish whether the bias was improved, the counts need to be positive. So that is one reason for adding the sum of negative counts as positive counts. I see it as a form of min-max scaling / pushing the signal above 0, although I know it is not completely the same for motifs. 

I can see how the negative counts might have a disproportionate weighting, but I never really looked into it that deeply to be honest... I am not sure if it is of much use to change anything in the code now, but if it turns out to be an issue, I will gladly take your further comments or suggestions!

Best regards,
Mette
