### ISSUE TITLE
differential test for paired samples

### ISSUE THREAD

**Issue by Dale12138** [loosolab/TOBIAS#108]
Hi Mette,
Thank you a lot for providing such an amazing tool! I was just wondering if paired-test (paired for the same biological replicates) for differential footprinting is available by Tobias? I would appreciate it so much if you could let me know!
Cheers,
Dale

**Comment by msbentsen** [comment]
Hi Dale,
Unfortunately TOBIAS doesn't deal with replicates, so there is no paired test. If your replicates are of good depth, you might run the tools per sample (rather than per condition), and then do your own statistics afterwards. But it is unfortunately not included in TOBIAS at this time, sorry!
Best Mette

**Comment by Dale12138** [comment]
Hi Mette,
Thanks a lot for your reply and clarification! It is good to confirm this!
Best Dale
