### ISSUE TITLE
Error with ATACorrect

### ISSUE THREAD

**Issue by tzhu-bio** [loosolab/TOBIAS#11]
![image](https://user-images.githubusercontent.com/54537420/78740936-9fb35800-798a-11ea-845f-21ed7f6878ee.png)
What is wrong with it?

**Comment by msbentsen** [comment]
Hi @tzhu-bio,

You will have to give me a bit more information, such as what version of TOBIAS you are running, what system (osx/linux) and the commandline call that prompted this error.

One thing I notice is that your regions are named "chr**0**1" instead of "chr1" - is this intentional? Did you map the .bam-file to those same chromosome names?

**Comment by tzhu-bio** [comment]
Thanks for your reply! Now I reinstall it and run successfully!
