### ISSUE TITLE
Read counts per peak

### ISSUE THREAD

**Issue by elia427** [loosolab/TOBIAS#114]
Hi,

Does the TOBIAS tool outputs raw read counts peak? I could see files under the peak_calling directory for each replication which looks like *sorted_raw.bed. However, there are no column names to it, so it is hard to know the fifth column is the read count, and nowhere in the documentation that explains the column names for files under peak_calling.

Thanks,
Elia

**Comment by msbentsen** [comment]
Hi Elia,

TOBIAS only does peak calling to find the open regions, so it does not write out the raw read counts per peak. The individual peak .bed-files are the output of MACS2 peak-calling and are in broadPeak format. ENCODE has an overview of the content of the different columns here: http://genome.ucsc.edu/FAQ/FAQformat.html#format13. None of those columns directly translate to raw read counts, but maybe something like `signalValue` will be comparable?

Otherwise, another solution would be to re-count the reads within peaks using counting-tools e.g. `featureCounts` or similar.

Best regards,
Mette

**Comment by elia427** [comment]
Thanks, Mette.

**Comment by msbentsen** [comment]
You're welcome - I will close this issue but free to get in contact in case of any other questions.
