### ISSUE TITLE
Snakemake pipeline documentation and problem with conda install TOBIAS_ENV

### ISSUE THREAD

**Issue by CharlesMagne** [loosolab/TOBIAS#115]
Dear Mette- thank you for this pipeline. I successfully installed and ran the snakemake pipeline in a miniconda3 environment. I had 2 problems that were related to required forms of input files: 
1. a gzipped version of the fasta genome file (fa.gz) could not be processed by samtools faidx in the pipeline. A block gz file (fa.bgz) was processed correctly.
2. UROPA does not accept gtf.gz compressed annotation files. I had to provide an uncompressed gtf file.
Perhaps it would be useful to explicitly indicate in the documentation that gz versions of these files are not accepted?

For another application, I would like to create a TOBIAS_ENV environment in miniconda3 on a remote Debian 9.5 Unix cluster in order to use individual TOBIAS commands outside of the snakemake pipeline. I proceeded as you suggested:
$ git clone https://github.com/loosolab/TOBIAS.git
$ cd TOBIAS
$ conda env create -f tobias_env.yaml
$ conda activate TOBIAS_ENV
The environment appears to have been created normally, but when I try running a command on the command line, bash returns command not found:
(TOBIAS_ENV) charles.magne@cluster:~/TOBIAS$ TOBIAS ATACorrect
-bash: TOBIAS : command not found
Do you have any suggestions as to how I can troubleshoot this problem ? Danke schön !

**Comment by msbentsen** [comment]
Hi @CharlesMagne,

Thank you for the issue report - you are indeed right, that the pipeline seems to complain about certain .gz files and that it would be good to have that documented. I have added some notes to the configuration file of the pipeline here: https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/commit/ff6cdf2b1429966ecf9b761e4427078d2680219d. Hopefully that is a help for the future!

Regarding installation, the `tobias_env.yaml` only contains the dependencies of TOBIAS - not TOBIAS itself. After creating the environment, you will need to install TOBIAS into the environment either using pip or conda as explained here: https://github.com/loosolab/TOBIAS/wiki/installation#dependencies. I recommend pip, just because it is faster, since you already have all the dependencies :-) Hope this solves your issue - otherwise please let me know!

BR Mette

**Comment by CharlesMagne** [comment]
Your explanation solved my TOBIAS installation problem- thank you !

**Comment by bioarpit1** [comment]
hi This issue seems to persist after providing uncompressed fasta for me 

here is the error message with test data and my data 

"Error in rule get_fasta_chroms:
    jobid: 16
    input: test1_output/flatfiles/hg38.fa
    output: test1_output/flatfiles/chromsizes.txt, test1_output/flatfiles/chromsizes.bed
    shell:
        samtools faidx test1_output/flatfiles/hg38.fa --fai-idx test1_output/flatfiles/chromsizes.txt;awk '{ print $1"  "0"     "$2 }' test1_output/flatfiles/chromsizes.txt > test1_output/flatfiles/chromsizes.bed
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
"

**Comment by bioarpit1** [comment]
![image](https://user-images.githubusercontent.com/29548776/219155886-2652bcce-7ffc-4ee7-bac6-7d552ad517ce.png)
