### ISSUE TITLE
MOTIFS File Generation

### ISSUE THREAD

**Issue by odagayev** [loosolab/TOBIAS#124]
Hi!

We're very excited to be using your tool for transcription factor footprinting. 

One question, for the BINDetest step. We are looking to have the analysis run on Homosapien CD8 T cells. Do you have any advice on which MOTIF inputs to use for this? Is this something that we have to generate on our own or is there a suggested data source?

Thank you very much.

**Comment by msbentsen** [comment]
Hi!
Yes, I can recommend something like the [HOCOMOCO](https://hocomoco11.autosome.org/) or [JASPAR](https://jaspar.genereg.net/) databases. Both have download options in .meme/.jaspar format, which TOBIAS BINDetect can read. You can also generate your own file, or use any other databases, as long as it is in these standard formats. If you already know what transcription factors are expressed in CD8 T cells, you might also filter your motifs to these TFs in order to limit the number of input motifs.

**Comment by odagayev** [comment]
To clarify my previous comment - I'm going to use the single batch text file located here (https://jaspar.genereg.net/downloads/) under the vertebrae tab. 

Thanks again for your help.

**Comment by msbentsen** [comment]
Yes exactly! You can use the vertebrate motifs [here](https://jaspar.genereg.net/download/data/2022/CORE/JASPAR2022_CORE_vertebrates_non-redundant_pfms_jaspar.txt). Not all of the motifs are originally found in human, but I think it is generally believed that the motifs are roughly conserved, so you can still use the "mouse" motifs for your human dataset. If you download the `_jaspar.txt` file, this can be used directly in TOBIAS.
