### ISSUE TITLE
Use TOBIAS with DNAse-seq data

### ISSUE THREAD

**Issue by hy09** [loosolab/TOBIAS#132]
Hi! Thanks for developing such an amazing tool! 

I was trying to apply TOBIAS with paired-end DNAse-seq data and I was hoping to get your feedback on the preprocessing I've modified:

1. Merged bam files from all biological replicates, filtered for only reads mapping in peak regions, and generated a bigwig file of only the 5' nucleotide positions with depth normalized to effective library size.
2. We had performed DNase treatment on naked DNA only to capture DNase cutting biases (referred to as Input). I then subtracted the input signal from the signals generated from my biological samples to correct for DNase biases. 
3. Used this corrected bigwig file for "scoreBigwig" and "BINDetect".

Any feedback would be helpful! Thank you very much.

**Comment by msbentsen** [comment]
Hi,

Thank you for your interest in TOBIAS! I am not so familiar with preprocessing DNAse-seq data, but my thoughts are:
- Although `TOBIAS ATACorrect` is created with ATAC-seq in mind, you could use it to learn the parameters of a DNAse-seq cutting bias as well. Setting `--read_shift 0 0` and `--k_flank 6` should be sufficient. Subtracting the input signal will also work, but will probably require deeply sequenced data in order to fully capture all positions of bias.
- In either case, you are definitely correct to use the corrected 5' position bigwig file as input for scoreBigwig, and the subsequent output for BINDetect!

I hope you will get some useful results with this package even if it was optimized for ATAC-seq.

**Comment by hy09** [comment]
Thank you for the detailed reply! I did get some interesting results by subtracting the input. I'll also try just estimating the cutting bias using `ATAcorrect`. 
Thanks again!
