### ISSUE TITLE
Meaning of the values in the bias bigwig file

### ISSUE THREAD

**Issue by HYsxe** [loosolab/TOBIAS#134]
Hi Tobias team,

Thanks for making such a great algorithm! It's been really inspiring for a lot of the projects in our lab.

I have been wondering what the values in the bias bigwig file mean. It seems that there are some negative values. Is this the raw bias after log2 transformation? If I want to use your predicted bias values to calculate the probability ratio of Tn5 instertion at any two bases (i.e., P(cutting at base A) / P(cutting at base B)), what should I do?

Thank you so much!

Regards

**Comment by msbentsen** [comment]
Hi,

Thank you for your interest in TOBIAS! The bias bigwig file contains the raw bias signal from the estimated Tn5 "motif", which is indeed the log2 of the bias/background score. This bias is then used to estimate the "expected" signal, by scaling it to the input counts of the individual regions. Because we divide by background, negative bias values mean that Tn5 is actually less likely to cut at these positions. We have seen cases of this where a TF motif looks like it has a footprint due to this effect, so it is important to also keep those in mind (not only the increased preference). Positive bias values mean that Tn5 has a stronger preference towards these positions than background. 

For comparing the values, you might directly investigate the range: `P(cutting at base A) - P(cutting at base B)` since it is already in log scale. Or you can convert the bias back to the original scale, and then compare those. However, I must say that I never worked with directly comparing the bias, so I would be very interested to hear how it turns out :-)

Best Mette

**Comment by HYsxe** [comment]
Wow thank you for such a quick response! Just to make sure I understand correctly, if you have base position A, B and C with bias score in the bigwig file being -1, 0, and 1, and let's say we observe in total 6000 cuts falling onto these three positions in total, we expect the distribution would be roughly 1000, 2000, and 4000 cuts for A, B,  and C, respectivelu. Is that correct?

Thank you so much!

**Comment by msbentsen** [comment]
Something like that, yes. The only point to mention is, that below a certain point of bias, you will not get less counts than 0... you will just get 0. So there is also a dynamic threshold set for the bias, such that low bias just translates to 0 counts.

Here is an example of this idea:
![image](https://user-images.githubusercontent.com/47495444/166891716-abd3b9b9-6789-4926-bad8-6c00d6e142d2.png)

It means that not all bases have an expected count, even if all bases have a bias score. Hope it makes sense!

**Comment by msbentsen** [comment]
You're welcome! I will close this issue here, but feel free to reopen in case of additional questions.
