### ISSUE TITLE
Interpreting binding score distribution

### ISSUE THREAD

**Issue by JohnsonStev** [loosolab/TOBIAS#139]
Hi,

I am examining the TF binding profile of the same tissues from two species.
My plan is to do differential binding analysis of different tissues within species, and than manually compare the results between species.

For species A, which have reads around 200M, the scores distribution peaked at ~ 0.15, with a density of ~7.5

For species B, which haves reads around 140M, has a tall peak at score = 0, density = 10, with another lesser peak at scores= 0.5, density = 1.5

Does this result indicate that species B have lots of low quality information, possibly due to lower coverage?

Thank you.

**Comment by msbentsen** [comment]
Hi,

I am not sure if you will be able to compare the values between species, as the normalization in the bias correction step (TOBIAS ATACorrect) only takes into account the number of reads, and the percentage of these reads in peaks. So it does not normalize towards different genome sizes, and the values might therefore not be comparable.

You should be able to compare the differential scores, because these are normalized within conditions, but not the raw distributions unfortunately.
