### ISSUE TITLE
results from time-series and simple comparison differ

### ISSUE THREAD

**Issue by alexyfyf** [loosolab/TOBIAS#145]
Hi team, 

I've been using TOBIAS for a while and it runs smoothly. But recently, when I compared results from a time-series result and a simple comparison result, the scores and differences differed.

Let me explain it, I had 3 conditions WV WEC WLC, and first I made a time-series comparison with WV-WEC-WLC, and I got a full table with mean_score and bound in each condition. 
```
# Command line call: TOBIAS BINDetect --motifs ../../Lmo2_ATAC/tobias_result/JASPAR2020_CORE_vertebrates_non-redundant_pfms_jaspar.txt --signals WT_veh/WT_veh_footprints.bw WT_EC/WT_EC_footprints.bw WT_LC/WT_LC_footprints.bw --genome /Myvolume/fyan0011/ref/mmu/ucsc_mm10/mm10.fa --peaks peaks/merged.bed --outdir BINDetect_WT --time-series --cores 12 --cond-names WV WEC WLC
```
Since the time series only compared adjacent conditions, i.e. WV vs WEC and WEC vs WLC, I also want to check the difference between WV vs WLC. I thought I can use the time-series result table and simply subtract WV_mean_score and WLC_mean_score, but I also did another run with only WV and WLC.
```
# Command line call: TOBIAS BINDetect --motifs ../../Lmo2_ATAC/tobias_result/JASPAR2020_CORE_vertebrates_non-redundant_pfms_jaspar.txt --signals WT_veh/WT_veh_footprints.bw WT_LC/WT_LC_footprints.bw --genome /Myvolume/fyan0011/ref/mmu/ucsc_mm10/mm10.fa --peaks peaks/merged.bed --outdir BINDetect_WLC2V --time-series --cores 12 --cond-names WV WLC
```
The result table was not the same when I check the mean_score and bound columns, although total_tfbs column is the same. Is that expected?

Could you help to clarify that? Thanks so much.

**Comment by msbentsen** [comment]
Hi,

It is a good question - the answer is that it is expected. The reason is that the conditions are normalized against each other, so the normalization of WV vs. WEC is different than the one for WV vs. WEC vs. WLC. Therefore the estimation of the footprinting scores (which effects mean scores and bound TFBS) will be different depending on the input conditions.

But if the third condition does not have huge influence on the normalization, I would expect the results to show the same upregulated TFs (only with a bit different values). Is this the case?

BR Mette

**Comment by alexyfyf** [comment]
Thanks for your explanation. 
I have not systematically compared the results, but by eye-balling, the numbers of TFBS and mean scores are quite similar. 
Another question may be related, how did you define bound TFBS? I don't quite get why the numbers of bound TFBS are also different, although I can understand the normalisation could change the mean score. 
Thanks in advance.
Alex

**Comment by msbentsen** [comment]
Hi Alex,

The estimation of bound vs. unbound TFBS is made in relation to the shape of the total score distribution (also described here: https://github.com/loosolab/TOBIAS/issues/141#issuecomment-1140217072). It is assumed that the upper tail of the lognormal distribution of scores is the bound subset. So that might be the reason why the number of bound TFs changes slightly in response to the score distribution changing as well.

BR Mette

**Comment by alexyfyf** [comment]
Thanks a lot for the explanation. I'll close this.
