### ISSUE TITLE
CreateNetwork

### ISSUE THREAD

**Issue by quangdang1998** [loosolab/TOBIAS#156]
Hi, this tool has been great and gave me some promising results. I'm reaching out to discuss the usage of the CreateNetwork tool. I notice that the 4th column of my bed files has a motif code appended to it (after running Bindetect):
....
chr1 3012659 3012666 Alx3_MM00383 5.13713 - chr1 3012657 3012855 . . ENSMUSG00000051951 Xkr4 0 0.21341
chr1 3400089 3400096 Alx3_MM00383 5.13713 + chr1 3398881 3400166 . . ENSMUSG00000051951 Xkr4 0.15627 0.07552
chr1 3424131 3424138 Alx3_MM00383 5.13713 + chr1 3424050 3424776 ENSMUSG00000051951 Xkr4 0.08238 0.17942
chr1 3436000 3436007 Alx3_MM00383 5.13713 + chr1 3435920 3436190 . . ENSMUSG00000051951 Xkr4 0 0.17983
chr1 4766816 4766823 Alx3_MM00383 5.13713 - chr1 4766356 4767040 . . ENSMUSG00000033845 Mrpl15 0.13758 0.57769...

Alx3_MM* doesn't match the name in my motif2gene file, which is only Alx3. I wasn't sure why the motif number was appended to the gene name, and CreateNetwork doesn't run as a result. I wonder if you have any ideas for solving this (I should modify the motif2gene file, probably). I reckon the issue may come from my motif file used in Bindetect, which I generated by amalgamating different motif databases (not just Jaspar). I would greatly appreciate any guidance, thank you!

**Comment by quangdang1998** [comment]
To modify my question, I notice that the 4th column of my bed files have a motif code appended to it: 
....
chr1	3012659	3012666	Alx3_MM00383	5.13713	-	chr1	3012657	3012855	.	.	ENSMUSG00000051951	Xkr4	0	0.21341
chr1	3400089	3400096	Alx3_MM00383	5.13713	+	chr1	3398881	3400166	.	.	ENSMUSG00000051951	Xkr4	0.15627	0.07552
chr1	3424131	3424138	Alx3_MM00383	5.13713	+	chr1	3424050	3424776			ENSMUSG00000051951	Xkr4	0.08238	0.17942
chr1	3436000	3436007	Alx3_MM00383	5.13713	+	chr1	3435920	3436190	.	.	ENSMUSG00000051951	Xkr4	0	0.17983
chr1	4766816	4766823	Alx3_MM00383	5.13713	-	chr1	4766356	4767040	.	.	ENSMUSG00000033845	Mrpl15	0.13758	0.57769...

Alx3_MM* doesn't match the name in my motif2gene file, which is only Alx3. I wasn't sure why the motif number was appended to the gene name, and CreateNetwork doesn't run as a result. I wonder if you have any ideas for solving this (I should modify the motif2gene file, probably). Thanks!

**Comment by sufyazi** [comment]
Hi, I am not sure if you are still facing this problem because this was almost a year late and you already closed this issue, but I am reopening it to share what I did to circumvent this in case someone else is reading and finding this troublesome.

Currently it seems like TOBIAS doesn't split the input motifs down to the motif ID and the associated TF name, (though I am not sure if it should) so the outputs of `binDetect`, specifically the bed files that you want to use with `CreateNetwork`, should be pre-processed first to work around this limitation.

I used `bash` for this alongside `awk` to do this easily. First I copied all the `bound.bed` files into a `tmp` folder to work with.

`find /path/to/outputs/tobias_o/bindetect_o/[dataset] -wholename "*/beds/*_[dataset]_bound.bed" -exec cp {} /path/to/tmp/tfbs_bounds/[dataset] \;`

The error occurs due to the naming conflict in the resulting `bed` files. To be consistent with the `--origin` table where only the protein/TF names are available, we should change the 4th column for all bed files from [TF name]_[motif ID] to just [TF name]. This can be done by simple `awk` manipulation as below. Note that these bed files are just copies, so do not worry if you mess this step up (though my `bash` script below should work fine; copy this into a text file, save it as .sh script, change permission to execute using `chmod +x path/to/script.sh`, then execute it by typing `./script.sh` on the commandline). 

```
#!/usr/bin/env bash

# directory to traverse
dir="/path/to/tmp/tfbs_bounds/[dataset]"

# loop through all files in the directory
counter=0
for file in "$dir"/*; do
    # skip directories
    if [ -d "$file" ]; then
        continue
    fi
    # alter the 4th column value using awk
    awk -F'\t' '{sub(/_[^_]+$/, "", $4); print}' OFS='\t' "$file" > temp && mv temp "$file"
    let counter++
    printf '%s\n' "$file successfully edited: [$counter]"
done
```
The resulting `bound.bed` output files can now be used with `binDetect`.
