### ISSUE TITLE
Peak within footprint region

### ISSUE THREAD

**Issue by loganminhdang** [loosolab/TOBIAS#157]
Hi, this is probably a simple question, but can footprint regions still have peaks? I'm talking about a case such as this: 

![image](https://user-images.githubusercontent.com/105299246/179998043-9461221c-a94d-43f3-82c8-740d6b4d3d11.png)

I wouldn't expect footprints to have this trace (normally, we see a dip indicating transcription factor binding and don't observe such a sharp peak). I wonder if you know what this peak may mean?

**Comment by msbentsen** [comment]
Hi,

Yes, a footprint might still have peaks in the middle. I have seen this quite a lot, and I don't know how to explain it biologically, but it might be some Tn5 bias leftover which was not able to be corrected. Could also be a true biological signature of whatever TF is binding there, which is not fully understood yet. In such cases, I would still say that `SCNSD` has a stronger footprint than `SCNCT` due to the total height of the signal.

For the error message, can you create a second issue for that? It helps me keep the issues separated. Thank you!
