### ISSUE TITLE
Which value is more "raw" in the output of "BINDetect" step?

### ISSUE THREAD

**Issue by lynnyummy** [loosolab/TOBIAS#158]
Hi, I am trying to use the results in `BINDetect` to do an extra transformation based on the "raw value". 

I am thinking of which value is more "raw" (similar to the `TPM` in RNA-seq analysis)? the `<condition>_mean_score` or `<condition>_bound`?

Thank you very much for your helps!

**Comment by msbentsen** [comment]
Hi,

I would say `<condition>_mean_score` is the comparable value to `TPM`, as this contains the raw signal of the footprints and is independent on the number of sites. Just like with TPM, it is not necessarily the genes/TFs with the highest mean_score which are the most important, which is why we often look at the changes across conditions (like differential expression). I hope this helps you out!

BR Mette

**Comment by lynnyummy** [comment]
> Hi,
> 
> I would say `<condition>_mean_score` is the comparable value to `TPM`, as this contains the raw signal of the footprints and is independent on the number of sites. Just like with TPM, it is not necessarily the genes/TFs with the highest mean_score which are the most important, which is why we often look at the changes across conditions (like differential expression). I hope this helps you out!
> 
> BR Mette

Hi @msbentsen, thanks for your explanation! I have tried both and they did have completely different outcomes.. anyway, thank you very much for your help!
