### ISSUE TITLE
Understanding significance values out of BINDetect

### ISSUE THREAD

**Issue by jordipla** [loosolab/TOBIAS#163]
Hi! First and foremost, thank you for developing and maintaining such an amazing tool.
I have used TOBIAS to make a simple comparison between control cells and knockdown cells for two proteins. I have gotten differential binding for several different motifs, and I would like to understand a little bit better the statistics behind the analysis.  
Basically my question would be, what makes a motif significant, and not others. 
I have detected both Trl and Pho as differentially bound between conditions. However, I would like to understand why other motifs with lower p_value and higher log2FC between conditions are not considered as significant (see volcano attached and differential binding plots).  
Thanks before hand!  
Best regards,  
Jordi  
[BEAF-32_MA0529.2_log2fcs.pdf](https://github.com/loosolab/TOBIAS/files/9647695/BEAF-32_MA0529.2_log2fcs.pdf)  
[pho_MA1460.1_log2fcs.pdf](https://github.com/loosolab/TOBIAS/files/9647687/pho_MA1460.1_log2fcs.pdf)  
[Trl_MA0205.1_log2fcs.pdf](https://github.com/loosolab/TOBIAS/files/9647681/Trl_MA0205.1_log2fcs.pdf)  
[bindetect_figures.pdf](https://github.com/loosolab/TOBIAS/files/9647810/bindetect_figures.pdf)

**Comment by msbentsen** [comment]
Hi Jordi,

Thank you for your question - I hope I can explain this in a little bit better detail:
The threshold for "significance" is set according to the data, and it is always on the criteria: -log10(p-value) above the 95% quantile and/or differential binding scores smaller/larger than the 5% and 95% quantiles (top 5% in each direction). I set "signifcance" in quotes, as BINDetect will always highlight the top changed TFs in either direction, so this is rather a "selection" rather than a significance per say.

This means that the threshold can be different on the left/right side of the plot. If you want consistency, I would use the output `bindetect_results.txt` to manually select TFs based on the _change columns. Hope this makes sense!

BR Mette
