### ISSUE TITLE
Bed file with footprint locations

### ISSUE THREAD

**Issue by odovgusha** [loosolab/TOBIAS#168]
Is it possible to get footprint locations (based on some threshold) before applying BINDdetect using TOBIAS? I am interested to screen for locations where there is some footprint was detected but no known motif was present.
Currently, I can only get footprinting scores but I guess I need to threshold those myself using R or some other tool.

**Comment by msbentsen** [comment]
Hi @odovgusha,

No, unfortunately there is no direct way to get this - mainly because it is difficult to set the global threshold for "what is a footprint". That is why TOBIAS mainly works with the continuous footprint scores to compare between conditions.

For getting the scores from the bigwig, I can recommend you the python package **pyBigWig** (this is also the package used internally by TOBIAS). Here are some examples of how to open and extract values from a region: https://github.com/deeptools/pyBigWig#retrieve-values-for-individual-bases-in-a-range

I hope you find a solution!

BR Mette

**Comment by aseveritt** [comment]
Hi @msbentsen, 

I appreciate you taking the time to maintain this GitHub repo so well! It has really helped me apply TOBIAS so far. I wanted to ask a clarifying question on this issue since I'm in a similar position as the OP. 

I'm trying to detect footprints in a single condition that doesn't match a known motif. Do you recommend using the tool in this way? My understanding is that the tool provides "de novo footprinting scores", but not technically de novo footprints. In order to get from the bigWig to bed my plan was to 1) define a score threshold based on the average bound score following BINDetect  2) use pyBigWig to scan for regions where the score is above that threshold 3) find the set difference between bindetect output bed and this bed file. However, I'm wondering if I should go forward with this plan given you all would've likely provided this as an output if you wanted users to use the tool in this way. Any advice?

Amanda

**Comment by hschult** [comment]
Hi @aseveritt,

I'm a colleague of @msbentsen.
For TOBIAS this is out of scope but recently we created a pipeline that uses the footprinting score to find de novo footprints. You can find it [here](https://github.com/loosolab/denis/tree/main). It will also go a few steps further and use the de novo footprints to create motifs and provide analysis.

Best wishes
Hendrik
