### ISSUE TITLE
Comparing TF ChIP-seq and TOBIAS

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#191]
Hi,

I am comparing TOBIAS footprints for a certain TF with ChIP-seq data from that TF. I have an unusual observation that the TF tends to bind about 8 - 10 kb away from where the TOBIAS footprint is. I am looking at a particular family of genes and it seems to consistently be the case. Are these two different binding "events" or Is there an explanation for why this might be occurring?

Thanks.

**Comment by msbentsen** [comment]
Hi,

If there are no obvious differences in the genome assembly between the files (for example hg19 vs. hg38), it just means that the footprinting results do not recapitulate the ChIP-seq. If you have a quality ChIP-seq for a factor, I would trust that more, since footprinting is influenced by many additional effects, and is not factor-specific for TFs with high sequence similarity.

But since it is not directly related to the TOBIAS software, this is unfortunately not anything I can help you solve.
