### ISSUE TITLE
Interpreting "all" vs "bound" files

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#193]
Hi,

I have what might be a basic question. What's the difference between the "all" vs "bound" files? Does "all" mean all the motif occurrences in the open chromatin peaks, and "bound" means the motif occurrences in those open chromatin peaks that pass a certain FootprintScore?

I think I might have some ChIP-seq data, but the ChIP shows binding to an "all" site but not a "bound" site. How to interpret?

Thanks!

**Comment by msbentsen** [comment]
Hi, please have a look at the documentation here:
https://github.com/loosolab/TOBIAS/wiki/BINDetect#output

![image](https://user-images.githubusercontent.com/47495444/217788266-148e97bb-3e4d-4162-99cb-941f1f42bebc.png)

Exactly, all is all sites in open chromatin, whereas bound/unbound is the split of these dependent on the threshold.

**Comment by adelosan521** [comment]
The other thread got canceled but there is no way "nearby" binding sites don't validate the TF footprinting analyses (the distance is about 8 kb)? It seems strange that the ChIP-seq binding keeps occurring near the footprint sites. Is there a potential issue with the ChIP or limitations about its resolution?

**Comment by msbentsen** [comment]
Hi, yes I closed the other issue because it is not technically a TOBIAS-related issue. I am a bioinformatician and I manage the TOBIAS software, but I unfortunately can't help you with finding potential issues in ChIP-seq - I guess this requires more in-depth analysis of the ChIP-seq mapping, the peak-calling, mean distances between motifs/chip etc.
