### ISSUE TITLE
Where is this output generated from and other BINDetect output questions?

### ISSUE THREAD

**Issue by c2b2pss** [loosolab/TOBIAS#198]
Hi Mette,

Thanks for the excellent program and comprehensive TF analyses!  

I am only a "part-time" computational guy trying to pick my way through TOBIAS, and am still unsure how to determine what is significant or what scores mean.  I have read and re-read the wiki and the BINDetect ouput descriptions and read through other people issues -- but still not very confident about values.  

**Please bear with me.**

1. In the overall "bindetect_results.xls" file I do not see any q-values or adjusted p-values (BH or otherwise) files.  Why is this? In image below the last column just says  "<condition B>_<condition A>_p-value".  Is this an adjusted p-value?

![bindetect](https://user-images.githubusercontent.com/29780345/222005444-a97eeab6-d72b-4827-b758-f47aaa9ebc78.png)

2b. What is <condition_A>_score_mean -- is it footprint score? If that is so, does that measure the confidence in calling a footprint, i.e. a strong footprint vs weak one?

2c.  How is "<condition A>_<condition B>_change" score determined then?

3. In the results file in (2), does the "condition_mean" (score) come from a mean of the values for the specific <TF> from
"<TF>_<condition>_bound/unbound.txt"?  Is there a cut-off for a "good score" by itself or is this simply by p-value? For example, if one score is 0.15 and another 0.10 can I say one is  0.15/0.1 = 1.5 x better than the other.

4. In this issue  https://github.com/loosolab/TOBIAS/issues/186   the user shows a result table? Where is the generated from?

I really would appreciate your input, and thank you for your time reading my questions!!

Thanks!

**Comment by msbentsen** [comment]
Hi @c2b2pss,

Thank you for your interest in TOBIAS! I will try to do my best to answer your questions here:

1. The p-value is not adjusted, no. The reason for this is that `TOBIAS BINDetect` uses an arbitrary threshold for filtering the final volcano-plot, and adjustment will therefore not change the final selection of TFs. Historically we also discussed that the p-values might not be independent due to overlapping motifs.

2b: Yes exactly, this is the footprint score. I have copied an explanation from the wiki:
![image](https://user-images.githubusercontent.com/47495444/222383401-65ee3437-8604-483a-9a56-0f0396e87ebc.png)

2c: The change score is determined by the difference in log2fc's between the observed sites, and a background distribution of sites. For each TF in the `TOBIAS BINDetect` run, you will see a plot in `<TF>/plots/<TF>_log2fcs.pdf` which looks like:
![image](https://user-images.githubusercontent.com/47495444/222384318-29dfd6bf-5f8a-4068-806d-49494249fbe0.png)
The comparison to a background helps to control for situations where one sample have globally higher footprint scores 8which would otherwise skew the comparison).

3. Yes the condition mean is the mean of all scores. For comparing between conditions, I would use the `_change` column. This score is an effect size, so I would set a rough lower minimum threshold of +/- 0.2 to highlight the most changed TFs.

4. The result table in the issue seems to be the output described here:
![image](https://user-images.githubusercontent.com/47495444/222386036-bd2c1130-676d-4611-bc69-7562baaeab05.png)
All columns of the input peaks file is written into the output files as well, so all the additional columns are coming from the user's input file. In this case, the 5th column is not the footprint score, but the TFBS score, as it says in the documentation.

Hope this answers your questions!
