### ISSUE TITLE
Is TOBIAS suitable for CUT&Tag of H3K27ac for footprinting detection?

### ISSUE THREAD

**Issue by xflicsu** [loosolab/TOBIAS#202]
Hello TOBIAS developer,
I read the paper published by [Steven Henikoff](https://www.nature.com/articles/s41467-019-09982-5#auth-Steven-Henikoff).
They show  "CUT&Tag protects a “footprint” spanning 80 bp directly over the CTCF motif". 
And the similar footprints were obtained using different salt concentration washes in their Fig. 5c.

Furthermore, [Guo-Cheng Yuan](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1802-4#auth-Guo_Cheng-Yuan) developed the CUT&RUNTools to perform CUT&RUN processing and footprint analysis.

Both ATAC-seq and CUT&Tag are based on Tn5 enzyme digested enrichment experiment. 
I wonder whether the TOBIAS is suitable for the CUT&Tag of H3K27ac for footprinting analysis?

**Comment by msbentsen** [comment]
Hi @xflicsu 

We have not validated TOBIAS on CUT&Tag data, so I cannot say whether it works or not. In theory, it should work, but there might be a few potential issues:
- If the CUT&Tag is for H3K27ac, any Tn5 footprints will be exclusively found in H3K27ac-rich regions
- In the same context, you might have to provide peaks/"regions of interest" that are larger than the peaks you would classically find for CUT&Tag, as you are also looking slightly outside of the signal region.
- I don't know how the Tn5 bias is affected by the CUT&Tag protocol, as ATAC-seq uses Tn5, but CUT&Tag uses pA-Tn5

So I would say, if there is already a tool developed specifically for CUT&Tag, it's better to use that. Otherwise you might try out TOBIAS and see if the CTCF shows a visible footprint like shown in the paper above. That might be a good test to see if it worked. Hope that is helpful!

**Comment by xflicsu** [comment]
Thanks for your suggestion.
I will try to figure out this issue.
