### ISSUE TITLE
FootprintScores runs extremely slow in 0.15.1

### ISSUE THREAD

**Issue by maxdudek** [loosolab/TOBIAS#216]
Hi, 

I've been able to run FootprintScores with no problem previously, but a few days ago I ran it for about 24 hours, and it only got to 1.0% completion. The output file was still being written to regularly, so this sudden slowdown was very odd. Unfortunately I only had the verbosity at 2 so I don't have any informative logs, but it seemed to be doing the same thing it normally did except much slower. 

I reverted back to 0.15.0 and it started working fine again, so I'm assuming that this has something to do with the new version, even though I couldn't see any significant changes in the code/patch notes. Posting here to see if this can be replicated/fixed.

Thanks!

**Comment by msbentsen** [comment]
HI @maxdudek,

Which step was slowing down? Also, do you know if this is reproducible if you upgrade back to 0.15.1? There was a small change in the writing of excel files which might be the culprit, but I can't reproduce it here unfortunately. Otherwise it might be an installation error in the `0.15.1`, which was then solved by downgrading.

**Comment by msbentsen** [comment]
Actually - disregard the comment about excel files, since FootprintScores only writes out .bigwig. But if you can reproduce it again, please let me know, then I will have a closer look!
