### ISSUE TITLE
What's the meaning of the Column 5 score in the TOBIAS TFBScan output

### ISSUE THREAD

**Issue by Rivers-Lee** [loosolab/TOBIAS#220]
Hi,

Thank you very much for providing such a helpful tool. I want to ask about the meaning of the Column 5 score in the TOBIAS TFBScan output. Is it a reflection of the degree of match between TFBS and DNA sequences? What I understand is that the higher the score, the better match the motif and the DNA sequence provided. Why does it have a negative value? Here is an example of my output.

Group2:1090396-1090925	1	17	GB40142_M06165_2.00	-3.46008	-
Group2:1090396-1090925	1	18	GB45074GB45076GB50686_M03519_2.00	-1.49204	+
Group2:1090396-1090925	1	18	GB45075_M03983_2.00	-10.91544	+
Group2:1090396-1090925	1	18	GB48450_M03975_2.00	1.07706	+
Group2:1090396-1090925	1	9	GB52601_M01657_2.00	4.94097	+
Group2:1090396-1090925	2	11	GB54355_M04661_2.00	0.46721	+
Group2:1090396-1090925	2	14	GB53318_M03636_2.00	0.79179	+
Group2:1090396-1090925	2	14	GB53401_M03648_2.00	0.73879	+

**Comment by msbentsen** [comment]
Hi,

Yes indeed, the 5th column is the score of the TF motif against the genomic sequence i.e. how well does the motif fit to the sequence. A higher score is a better match.

Dependent on your background GC content, some of the matches could become significant even if the score is negative. This is because the final TFBS score threshold is dependent on the score from the background content. You can adjust this with the `--gc` parameter. It also depends on the threshold set in `--pvalue`. We are using the scoring library MOODS (https://github.com/jhkorhonen/MOODS), in case you want to reproduce the calculation outside of TOBIAS.

But all in all, I would say it is not an issue if you have set appropriate parameters to the function.

**Comment by Rivers-Lee** [comment]
Thank you, that makes sense.
