### ISSUE TITLE
motif file format

### ISSUE THREAD

**Issue by drosop** [loosolab/TOBIAS#223]
Hi,

I have a motif file in homer format. I tried to convert it to PFM format using [MonaLisa](https://fmicompbio.github.io/monaLisa/articles/monaLisa.html) with the following script:

homerToPFMatrixList(filename = "CuratedTF.motifs", n = 100L)

I have two questions: 

1. Does TOBIAS take homer format motif file?

2. If Im converting homer to PFM, is there any other recommended method, other than using MonaLisa? 

Thank you so much for the help!

**Comment by msbentsen** [comment]
Hi @drosop ,

I am not aware of what the homer motif format specification looks like - can you share an example? 
TOBIAS reads motifs in jaspar / pfm / meme formats, but since I never worked with homer I can unfortunately not give you recommendations for how to convert. But if homer is a well-established format with a clear specification, I would be happy to include that as an input possibility in a future TOBIAS version.

BR Mette

**Comment by drosop** [comment]
Hi Mette,

This is HOMER format. 

http://homer.ucsd.edu/homer/ngs/formats.html

Basically, each motif within the file contains a header row starting with a ">", followed by several rows with 4 columns, specifying the probabilities of each nucleotide at each position.
>ASTTCCTCTT     1-ASTTCCTCTT    8.059752        -23791.535714   0       T:17311.0(44 ...
0.726   0.002   0.170   0.103
0.002   0.494   0.354   0.151
0.016   0.017   0.014   0.954
0.005   0.006   0.027   0.963
0.002   0.995   0.002   0.002
0.002   0.989   0.008   0.002
0.004   0.311   0.148   0.538
0.002   0.757   0.233   0.009
0.276   0.153   0.030   0.542
0.189   0.214   0.055   0.543

The first row starts with a ">" followed by various information, and the other rows are the positions specific probabilities for each nucleotide (A/C/G/T).  These values do not need to be between 0-1.

Thank you,

**Comment by mishrabi** [comment]
very much interested in this as well. Thank you for Tobias, it it a quite informative tool... many people are used to working with homer and would be nice to integrate home into Tobias pipeline.

**Comment by msbentsen** [comment]
Hi all,

Due to the format of homer being very similar to the one of JASPAR PFM (starting with > followed by lines of counts), it is difficult to distinguish these as input for TOBIAS. Instead I made a small script to convert any homer motifs to this format for input in TOBIAS:
https://gist.github.com/msbentsen/c32cc96ca5b9abe4f8fa88c86fc95e1b 

You can use this as:
```python homer2pfm.py --input homer_motifs.txt --output converted_motifs.txt```

So given an input of a homer motif, e.g.
```
>VTGACTCATC	AP-1(bZIP)/ThioMac-PU.1-ChIP-Seq/Homer	6.049537	-108.866256	0	T:120.0(38.96%),B:4197.9(8.55%),P:1e-47
0.419	0.275	0.277	0.028
0.001	0.001	0.001	0.997
0.010	0.002	0.965	0.023
0.984	0.003	0.001	0.012
0.062	0.579	0.305	0.054
0.026	0.001	0.001	0.972
0.043	0.944	0.001	0.012
0.980	0.005	0.001	0.014
0.050	0.172	0.307	0.471
0.149	0.444	0.211	0.195
```

You will get a pfm-style output as:
```
>AP-1(bZIP)/ThioMac-PU.1-ChIP-Seq/Homer
0.419	0.001	0.010	0.984	0.062	0.026	0.043	0.980	0.050	0.149
0.275	0.001	0.002	0.003	0.579	0.001	0.944	0.005	0.172	0.444
0.277	0.001	0.965	0.001	0.305	0.001	0.001	0.001	0.307	0.211
0.028	0.997	0.023	0.012	0.054	0.972	0.012	0.014	0.471	0.195
```

These can be then be used directly as TOBIAS input. Hope that helps!
