### ISSUE TITLE
Threshold for TF Footprints/Multiple Overlapping Footprints in PlotTracks

### ISSUE THREAD

**Issue by beginnertobioinformatics** [loosolab/TOBIAS#229]
Hello,

I sincerely apologize for the multiple posts. I am trying to use BINDetect and PlotTracks to determine differential transcription factor binding at certain sites in the genome and had a couple, related questions--

I ran PlotTracks for a few regions of interest and got a result similar to below. I wanted to know whether there was a recommended threshold/cutoff for the values (averages?) shown at the left-hand side for the _corrected and _footprints bigwig files (13.31, 13.31, 3.75, and 3.75 on the screenshot)? When I ran the test data, it seemed like the values were much higher. Similarly, is the number of overlapping footprints a cause for concern in my data, or is it simply a consequence of the region I'm looking at/the similarity in motif sequence (as determined in BINDetect with my JASPAR file) within that region?

<img width="510" alt="PlotTracks Example" src="https://github.com/loosolab/TOBIAS/assets/138829160/07fa771a-1fcb-4686-8669-3b16114d5dfc">

Thank you so much for your insight! This tool has been incredibly helpful.

**Comment by msbentsen** [comment]
Hi @beginnertobioinformatics ,

The values in the test-data will be different than real data because the dataset is much smaller - so I would not compare the values with other analysis. We usually don't set a threshold on the y-axis, as this is defined during the BINDetect run. So the output TFBS will reflect whether a TF was assigned bound or not. In this example, it does not look like there is too much difference between the two conditions, as you can see roughly similar "corrected"-signals (but maybe slighly higher footprint scores in control).

The number of TFBS also seems normal. As you mention, motif similarity can lead to cases like Stat6, Stat5 and Stat5a-Stat5b motifs overlapping. I hope this answers your questions!

**Comment by beginnertobioinformatics** [comment]
Thank you very much-- I really appreciate the confirmation/explanation!
