### ISSUE TITLE
Memory issue BINDetect Module

### ISSUE THREAD

**Issue by ThorstenCodes** [loosolab/TOBIAS#234]
Thanks for the nice TOBIAS tool. ATACcorrect and ScoreFootprints run nicely. 
However i always run into a problem running BINDetect. Apparently it cannot finish/print the final files most of the time as usually following error occurs:

"BLAS: Progam is Terminated. Because you tried to allocate too many memory regions. "

Our servers have 250 G memory and 250G Swap and if i check in htop the memory is not fully used (so there should be enough memory) 
I set the --split 1000 , but that did not change the outcome. 

I run BINDetect on a normal ATAC Peak file having something like 180K peaks but also if I reduce the number of peaks in the file this occurs quite often (although sometimes it makes it through). Sometimes it also finished the full peak set but it fails in most cases. 

Our servers have 250 G memory and 250G Swap and if i check in htop the memory is not fully used. 
I set the --split also to 1000, gave him up to 60 cores but that did not change the outcome. 
Do you have any idea what could be the problem?  Or any tips who to circumvent the problem?

Thanks for your help:)

**Comment by msbentsen** [comment]
Hi @ThorstenCodes ,

Thanks for your issue. Since the error does not seem to come due to memory consumption, I suppose the issue is in the parallelization of the calculation. Can you give some more information on what system you are running on? Linux, Mac?

I found an old issue on stackoverflow with this same error, and here the solution was given to set `export OMP_NUM_THREADS=1`: https://stackoverflow.com/a/45086247 
Perhaps you can try this as well? Please let us know in case the issue persists.

**Comment by ThorstenCodes** [comment]
Hi Mette,

I apologize for the delayed response. I'm currently working on a Linux system, and apparently you were right and there might be an issue with parallelization. However, setting export OMP_NUM_THREADS=1 has resolved the problem. It does take a bit longer for the calculations, but there are no more memory problems. 
Thank you for your assistance:)
