### ISSUE TITLE
BINDdetect vs plotHeatmap

### ISSUE THREAD

**Issue by mbergsland** [loosolab/TOBIAS#247]
Hi
First of all, thanks a lot for such a nice and useful tool!

I have two sets of ATAC-samples; control cells and cells over-expressing TF A. I have ChIP-seq peaks for TF A which are the regions that I have investigated for footprints with TOBIAS. Importantly, centrally enriched TF Motif analysis of ChIP-seq peaks showed centrally enriched motif of TF A, but also a very strong centrally enriched motif of non-related TF B. With this background, my main question to solve with TOBIAS was whether TF A and TF B bind together or exclusive of each other (TF A is not expressed in control condition).
From BINDdetect, volcano plot shows TF A footprints and TF B footprints on each side which would, I guess, suggest that the 2 factors do not bind together but rather exclusive of each other (fig1). Considering the strong centrally enriched motifs of both factors within the examined peaks, I assume that the majority of the signals come from the center of these peaks
Higher score is shown for TF A in control sample (sample 204) and for TF B in sample with overexpression of TF A (sample 201) in the volcano plot (fig1). This does not make sense since TF A is overexpressed in sample 201 and should show stronger footprints than control sample 204 (binding of TF A is also confirmed from ChIP-seq).  Moreover, in the plots from plotHeatmap, footprints (fig2) from TF A is seen in sample 201 and not in sample 204. For TF B the footprint seem stronger for 201. These results seem to be opposite to what is seen in the volcano plot (TF A and TF B footprints increased in each sample, not the same), why is that? It would be very helpful to understand these data properly.
I also have a question regarding plotAggregate. Fig3 shows one single region with all footprint signals (bed file with one region), is zero referring to the middle of the peak in this case? What is zero referring to when several regions are analyzed by this function?
![Untitled-2](https://github.com/loosolab/TOBIAS/assets/11404560/e8fef75e-2ba7-49ff-ba54-a5cc8051bc82)

**Comment by mbergsland** [comment]
Thank you for your response.

I have been using the following commands,
For Tn5 corr and making bw files: 

`TOBIAS ATACorrect \
--bam 204_REP1.mLb-clN.sorted.bam --genome /Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa --peaks ChIPSeq_peaks.bed --cores 16 --outdir /Tobias/Footprint204/`

`TOBIAS ScoreBigwig \
--signal /Tobias/Footprint204/204_REP1.mLb-clN.sorted_corrected.bw --regions ChIPSeq_peaks.bed --cores 16 --output /Tobias/Footprint204/204_REP1.mLb-clN.sorted_footprints.bw`

And for BINDdetect and plotheatmap:

`TOBIAS BINDetect \
--motifs  /Tobias/non_redundant_motifs/all_motifs.txt --signals /Tobias/Footprint204/204_REP1.mLb-clN.sorted_footprints.bw /Tobias/Footprint201_Sox21ChIP/201_REP1.mLb-clN.sorted_footprints.bw --genome /Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa --peaks ChIPSeq_peaks.bed --cores 16 --outdir /Tobias/204_vs_201/BINDdetect`

`TOBIAS PlotHeatmap --TFBF /Tobias/204_vs_201_Sox21ChIP/BINDdetect/TF_B/beds/TF_B_all.bed --TFBS /Tobias/204_vs_201_Sox21ChIP/BINDdetect/TF_B/beds/TF_B_all.bed --signals /Tobias/Footprint204_Sox21ChIP/204_REP1.mLb-clN.sorted_corrected.bw /Tobias/Footprint201_Sox21ChIP/201_REP1.mLb-clN.sorted_corrected.bw --output TFB_heatmap.png --signal_labels nonDOX_204 DOX_201 --share_colorbar --sort_by -1`

plotHeatmap for TF A was done in the same way.

Since TF A and TF B have motifs close to each other (both are centrally enriched in peaks from ChIP-seq of TF A), could it be possible that the stronger footprint in 201 for TF B is in fact due to binding of TF A I this area (TF A is overexpressed in 201 and not expressed in 204)? However, this still would not explain why the two footprints show up on each side in the volcano plot whereas both of them seem enhanced in sample 201 with plotHeatmap function.

**Comment by msbentsen** [comment]
Hi @mbergsland 

Thank you for sending the commands, that's very helpful! I see that the commands were all run on the peaks of "ChIPSeq_peaks.bed", which only contain the chipseq peaks, correct? I am asking because during the `TOBIAS BINDetect` command, the input of all conditions is normalized towards each other to make all values fit an equal distribution. Since the input is only TF A locations, which might be largely closed in sample 204, the normalization might be skewed towards increasing scores in sample 204 artificially.

Can you try to run the commands on all open ATAC-seq peaks? For ATACorrect and Scorebigwig you can set `--peaks/--regions atac_peaks.bed`. In the final step of BINDetect, you can set `--peaks atac_peaks.bed --output-peaks chipseq_peaks.bed`, which will normalize based on all peaks but only build the volcano-plot based on the chipseq peaks. This will likely create a volcano plot heavy on the TF's enriched within the peaks, but might also show TF's underrepresented.

I hope this is helpful - otherwise please feel free to update here, thanks!

**Comment by apal6** [comment]
Hi. Following up on this issue. I have the same problem where the volcano plot shows a TF to be up in control group but the plot aggregate shows it's up in the treatment group (opposite results). I wondered what's causing this? Is it taking a different output file to plot the dip plot? Biologically, the Bindetect volcano plot makes alot of sense so we are keeping that as a benchmark. 

Thank you!

**Comment by apal6** [comment]
Hi @mohobein, thank you for explaining potential issues with my script. However, it looks like i am giving the right input- 

![Image](https://github.com/user-attachments/assets/10c99392-6b19-4a47-991c-94bd72325787)

command- 
`TOBIAS PlotAggregate --TFBS /Stat5b_MA1625.2/beds/Stat5b_MA1625.2_treatment_bound.bed /Stat5b_MA1625.2/beds/Stat5b_MA1625.2_control_bound.bed \
    --signals /treatment.mRp.clN.sorted_corrected.bw control.mRp.clN.sorted_corrected.bw \
    --output Stat5b_MA1625.2_TvsC_only_bound_sites.pdf --share_y both --plot_boundaries`

Thank you,
Aastha

**Comment by mohobein** [comment]
Thank you for sending the plots and the command.

You did indeed provide the right signal files, but the --TFBS bed files are not well suited for the comparison with the volcano plot. You are visualizing the average footprint at __bound__ TFBS only, and since bound sites are identified because there was a footprint, both aggregated signals look similar in shape. If you run check the total amount of bound sites in both conditions (for example by running `wc -l /Stat5b_MA1625.2/beds/Stat5b_MA1625.2_treatment_bound.bed /Stat5b_MA1625.2/beds/Stat5b_MA1625.2_control_bound.bed`, but the number on the corner of the PlotAggregate cells with just one condition should also show it), you will probably see that the control condition has many more entries, which causes the differential binding score to be skewed towards it.

To use PlotAggregate to visualize this difference, you need to provide the unbound sites as well. Then, the difference should be visible, as in the example on the wiki page: ![PlotAggragate bound/unbound split](https://github.com/loosolab/TOBIAS/blob/main/figures/BATF_footprint_comparison_all.png?raw=true)
Note how all TFBS were used to see the difference between conditions here.

Let me know if this visualization makes more sense with the results!

**Comment by apal6** [comment]
Thank you so much for the explanation. You said the bed files are not suited for volcano plots? Is it the bindetect volcano plot you are talking about or the dip plot with aggregated signal? The command that gave me the volcanoplot- 

`
TOBIAS BINDetect --motifs /JASPAR2024_CORE_non-redundant_pfms_meme.txt \
    --signals treatment.bw control.bw \
    --genome /genome.fa \
    --peaks /merged_peaks_with_info_treatmetnvscontrol.bed
 `

Yes the treatment has 5746 entries and control has 9675 entries.

here's the comaprison plot with bound sites only -
<img width="182" alt="Image" src="https://github.com/user-attachments/assets/d1fa4a57-cac9-4ca6-9fa3-fdadc8eb3b0b" />

When you say i need to give bound and unbound both the sites, this is what i should use to compare the dips?

$ TOBIAS PlotAggregate --TFBS test_data/IRF1_all.bed test_data/IRF1_Bcell_bound.bed test_data/IRF1_Bcell_unbound.bed --signals test_data/Bcell_uncorrected.bw test_data/Bcell_expected.bw test_data/Bcell_corrected.bw --output IRF1_footprint.png --share_y sites --plot_boundaries

Thank you,
Aastha

**Comment by apal6** [comment]
Thank you so much for your time to explain this concept to me. This is so so helpful! Really appreciate it. I was able to replicate the results from the volcano plot. :) 

Wondering if there is a way to normalize the bound region in the middle to compare the two conditions? I know Tobias does some normalization. 

Thank you!

**Comment by mohobein** [comment]
Glad I could help :)

TOBIAS normalizes the footprinting scores between conditions and compares them to a distribution of background scores. I am not sure what exactly you mean with normalizing the bound region itself? Could you perhaps explain what you wish to find out with that?
The scores are comparable, just the amount of data points is not when comparing the bound subset of TFBS (if differential binding is indeed occuring). If you just want to compared the average "strength" of bound footprints only, the plot you generate at first serves you well enough I suppose, but I am not sure how useful that results is, but perhaps your specific biological question might benefit from that. A little bit more detail on your research question might allow me to give better suggestions.
