### ISSUE TITLE
How to compare TOBIAS mean footprint scores called for each sample independently?

### ISSUE THREAD

**Issue by massonix** [loosolab/TOBIAS#258]
Hi,

Thanks for developing this wonderful tool!

I have ATAC-seq data for 3 cancer patients. For each patient, I have one sample pre-treatment and another post-treatment, for a total of 6 samples. Given that the data is paired, I'm running BINDetect for each sample individually:

```
TOBIAS BINDetect \
    --motifs data/jaspar/JASPAR2020_CORE_vertebrates_non-redundant_pfms_jaspar.txt \
    --signals results/ATAC-seq/tobias/${sample}_footprints_scored.bw \
    --genome results/ATAC-seq/genome/genome.fa \
    --peaks results/ATAC-seq/new_peaks/consensus_peaks_without_singletons_and_sex_chromosomes.bed \
    --outdir results/ATAC-seq/tobias/${sample} \
    --cond_names $sample \
    --cores $ncores
```

This generates a "bindetect_results.txt" file for every sample, which I aim to use to test for differential binding. I load it and get the difference in mean_scores between post and pre-treatment for every TF. However, I get this weird pattern, in which all TF have a higher TF footprint score in pre-treatment for patient one, and the opposite for patients 2 and

<img width="700" alt="image" src="https://github.com/loosolab/TOBIAS/assets/35916509/fa7ff698-2e0a-45b5-a900-2b7de2de8023">

Is there any bias that I'm not taking into account? Are the mean scores comparable?

Thanks a lot in advance!

Ramon

**Comment by hschult** [comment]
Hi Ramon,

thanks for using TOBIAS!

Since you are using the `mean_scores` that are computed as the average overall TFBS ([see here](https://github.com/loosolab/TOBIAS/wiki/BINDetect#output)) the results may be affected by outliers. This would especially be a problem when dealing with low numbers of TFBS (see the `total_tfbs` column). You could try to incorporate the `total_tfbs` into your analysis or look at the individual TFBS scores (found in `bindetect_output/<TF_A>/<TF_A>_overview.txt`) and start from there.

However, depending on your research question I recommend doing one BINDetect run per patient to find differential TFs for pre- and post-treatment for each patient or to do one BINDetect run per condition to identify differences in e.g. pre-treatment between the patients.

Kind Regards,
Hendrik

**Comment by massonix** [comment]
That's very informative, thanks a lot Hendrik! Keep up with the great work!
