### ISSUE TITLE
Installation problem - solving environment

### ISSUE THREAD

**Issue by sngholee** [loosolab/TOBIAS#267]
Hello,

I've tried to install TOBIAS a few times, and each time, I get stuck on Solving environment for 24+ hours, and have been terminating it. Is this expected? Should I let it run for longer?

`conda env create -f tobias_env.yaml
Collecting package metadata (repodata.json): done
Solving environment: / 
`

Thank you

**Comment by mohobein** [comment]
Hello @sngholee,

thank you for using TOBIAS.

Solving the environment should definitely not take this long, you are right. Have you tried using [mamba](https://github.com/mamba-org/mamba) instead of conda? That should be much much faster, not only for the TOBIAS installation, but all your python environments.

I hope this helps! If not, we can think about it further.

Best regards,
Moritz
