### ISSUE TITLE
BINDECT warning

### ISSUE THREAD

**Issue by StevenBai97** [loosolab/TOBIAS#285]
Hi,

When running TOBIAS BINDetect (v0.16.1), I encountered some warning messages, such as "/.conda/envs/tobias/lib/python3.12/site-packages/logomaker/src/matrix.py:270: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2 0.5 0.3 0.2 0.6 0.7 0.6 0.2 0.4 0.6 0.4]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first. prob_df.loc[:, :] = vals / vals.sum(axis=1)[:, np.newaxis]".

Would they affect the results of the BINDetect?

Thanks in advance and all the best

**Comment by hschult** [comment]
Hi @StevenBai97,

no this won't affect your BINDetect results. This is a deprecation warning of the logomaker package which we use to visualize the TF motifs. This is likely something the logomaker team has to fix within their package and not something we can do. They might have done this already. Since you are using an old TOBIAS version (the current is `0.17.0`) I recommend updating your environment. This could remove the warning.

But regardless of the warning being removed this won't influence any TOBIAS results.

Best wishes,
Hendrik
