### ISSUE TITLE
bindetect error

### ISSUE THREAD

**Issue by xiasijian** [loosolab/TOBIAS#294]
![image](https://github.com/user-attachments/assets/891fa2cd-36c6-4d48-9367-4159527eb37a)

**Comment by xiasijian** [comment]
Can you help please?

**Comment by xiasijian** [comment]
@mlooso @hschult @pgoymann @afust

**Comment by hschult** [comment]
Good morning,

please do not tag everyone to force an answer! This will not speed up the process, especially on a weekend. That being said, I need more information to help you. This only tells me that there is something wrong with bindetects p-value computation. Please re-run bindetect with `--debug --verbosity 5` and provide the log files. You can also try to run bindetect with our test data ([see here](https://github.com/loosolab/TOBIAS/wiki/test-data)) to find out whether this is related to your data. However, the best thing would be to provide a small reproducible example. This would allow me to reproduce the error, which is the easiest and fastest way to suggest a solution. For this either provide the bindetect call that runs into the error using the test data or a small subset of your data (the smaller the better).

Best wishes
Hendrik

**Comment by xiasijian** [comment]
I am sorry that I foget the time difference between different countries. So sorry about that. I do the things what you have suggested, but the error happened again even through I set the relaxed parameter of --motif-pvalue and --bound-pvalue. Is it related to the bam files? I have try your demo data, it ran well. Thanks a lot.
![image](https://github.com/user-attachments/assets/e6596c5f-d4cd-4607-9a52-2697535f24cf)
![image](https://github.com/user-attachments/assets/1a530f46-a03a-49c7-9011-9e3731a1c2ef)

**Comment by hschult** [comment]
Yes, since the test data ran without issue I assume it relates to your data. I suggest you load everything (genome, bigwigs, peaks, etc.) into IGV and check if everything lines up. To explain, [BINDetect](https://github.com/loosolab/TOBIAS/wiki/BINDetect) searches the peak regions for motifs (aka potential TF binding locations) and then decides based on the local signal (provided through bigwig) if the respective TF bound or not. So any of these files not lining up could result in e.g. no binding locations found, which could result in the issue you are experiencing.

Depending on what you are doing it may be worth looking into our [TOBIAS snakemake](https://github.com/loosolab/TOBIAS_snakemake) pipeline. This automatically takes care of running all the TOBIAS steps in order and with the correct files.

**Comment by xiasijian** [comment]
Thank you for such important information, I will double check my files and code based on this, thank you very much again!

**Comment by cammo0p** [comment]
Hi Sijian,

I’m encountering the same error that you mentioned previously and was wondering if you could share how you troubleshooted the issue. Did it relate to the lack of binding locations, which in turn caused the "IndexError: index -1 is out of bounds for axis 0 with size 0"?

I’ve posted an issue on the TOBIAS_snakemake GitHub page, which provides more details. You can find it here: https://github.com/loosolab/TOBIAS_snakemake/issues/23.

I’d appreciate your insight on the motif.txt file you used. I am working with human hg38 data—should I filter out the Homo sapiens motifs from the JASPAR motif file, or is it better to use the vertebrate motifs instead? 

Looking forward to hearing your thoughts!

Best regards,
Chloe
