### ISSUE TITLE
Question about TF_distance_matrix.txt

### ISSUE THREAD

**Issue by shangguandong1996** [loosolab/TOBIAS#36]
Hi, Dear developer
I have some questions about TF_distance_matrix. 
1. According to the below explanation

> Distance matrix used to cluster the transcription factors in the bindetect_figures-dendrograms. This is based on the overlap of individual transcription factor binding sites.

The calculation of the distance value is based on the TFBS , so it is from `<outdir>/<TF>/beds/<TF>_all.bed` ? So every distance tree in each page of bindetect_figures.pdf is same ?

2. What is the calculation method of distance ？ Is it Jaccard index?

3. Can I get the distance value of specific condition using the `<outdir>/<TF>/beds/<TF>_<condition>_bound.bed` ?  I think it may offers another information.

4. And Does `Cluster Motifs: Cluster motifs and create consensus motifs based on similarity` has relationship with the distance value? I think clusterMotifs is just based on the motif similarity without thinking TFBS.

And thanks for this wonderful tools 👍 :)
Best wishes
Guandong Shang

**Comment by msbentsen** [comment]
Hi Guandong,

Great question - I will answer below:

1. Yes, the calculation is based on all TFBS in open regions, so every distance tree is the same regardless of contrast. 

2. The calculation of distance is a form of modified Jaccard. Per TF-pair TF1 vs. TF2, it is the maximum fraction of overlap of sites for TF1->TF2 or TF2->TF1. This is explained in more detail in the supplementary methods of the paper [here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-18035-1/MediaObjects/41467_2020_18035_MOESM1_ESM.pdf) (page 11).  
3. Unfortunately, there is currently no way to get the distance information for a specific condition or a specific subset. However, if you are comfortable writing scripts yourself, I might be able to send you a few code snippets using the backend TOBIAS classes to do it - let me know.
4. You are correct, `ClusterMotifs` is a clustering based on motif similarity, whereas the dendrogram in BINDetect is based on the overlap of TFBS. However, because the TFBS are based on scoring of the motif, these two metrics have an indirect link. But you might say that the overlap of TFBS is sensitive to the context of the used `--peaks`, whereas motif similarity is not.

I hope this was helpful,
Best Mette

**Comment by shangguandong1996** [comment]
Thanks 👍 
And I have two issue :)
1. Maybe you can make additional utility tool to specificly plot **the part** in the next release, just like below. After all, ploting the whole distance tree + whole differential binding score may not realistic.
By the way, this plot is wonderful :)
![图片](https://user-images.githubusercontent.com/22555126/96250584-a7128880-0fe1-11eb-8a14-186e3574c5b6.png)

2. I am wondering whether the text in y-axis should be **Transcription factor distance** instead of **Transcription factor similarities** ?
![图片](https://user-images.githubusercontent.com/22555126/96250717-dcb77180-0fe1-11eb-9198-04dad51dff88.png)


Guandong Shang

**Comment by msbentsen** [comment]
Hi Guandong,

1. This a good idea - I will add an enhancement tag and see if I can add this in a future version.
2. Yes, for clarity, you are right that it should probably be "Transcription factor distance" or "Transcription factor overlap". Thank you for pointing this out! 

Best Mette

**Comment by msbentsen** [comment]
I have just released `TOBIAS 0.12.3` containing a utility script called `cluster_sites_by_overlap.py`, which creates the distance matrix and dendrogram for a subset of sites. As an example, to get the clustering of sites in the bound subsets, you can run it with:
`cluster_sites_by_overlap.py --bedfiles BINDetect_output/*/beds/*Bcell_bound.bed`

Because of the internal normalization in BINDetect, it is not possible to calculate the differential footprint scores on a subset of sites (as the scores would then be shifted with regards to the background scores). So this plot only gives you the dendrogram of overlapping sites. I hope it helps you nonetheless!

**Comment by shangguandong1996** [comment]
Hi, Mette.
I just think another issue about your calculation of distance. According to your paper, you use the motif site location overlap
![图片](https://user-images.githubusercontent.com/22555126/97436215-960c3480-195c-11eb-985b-2c6cfc707cc8.png)


And I think it will cluster mostly based on motif similarity as you said. In other words, it will cluster the motif family. And I am wondering whether I can produce more biological clustering meaning if I calculate distance just base on the Jaccard distance of peak overlap. After all, Two cooperative TF may located in same peak, but may not located one next site in same peak.
For example, 
- TF1 in peak1,2,3
- TF2 in peak2,3,4,5
So the distance is 1 - 2/5 = 0.6

If I misunderstand something, please forgive me :)

Best wishes
Guandong Shang

**Comment by msbentsen** [comment]
Hi Guandong Shang,

The reason why the distance is calculated by TFBS overlap is to get an idea of possible false-positive footprints within motif families. E.g. if a factor such as GATA4 is found to have a footprint, the distances will show that GATA2, GATA3, etc. are also very similar. We can therefore not be sure which of the proteins is actually causing the footprint. 

You could probably calculate a distance based on the cooperation of TFs - but this is a different problem than what is being solved by TOBIAS. You can create a TF x peaks matrix from the "TOBIAS BINDetect" output files, as you have all information of which peaks each TFBS was found within. Sounds interesting, but it is not something that I am going to get into at this point :-)

Best Mette

**Comment by shangguandong1996** [comment]
Thanks for your reply :) I get it.
