### ISSUE TITLE
The meaning of meanscore in data-tobias-2020/Tcell_bindetect_results.txt

### ISSUE THREAD

**Issue by shangguandong1996** [loosolab/TOBIAS#39]
Hi, Mette
I do not know it is a question or finding ╮（╯＿╰）╭. So I just post a issue.
I found many TF in my data do not have apparent footprint tendency, just like following picture
![图片](https://user-images.githubusercontent.com/22555126/97539973-e091bd80-19fd-11eb-945b-da248d661c01.png)

But I did found some TF have beautiful tendency, and all these TF have **high meanscore** in my bindetect_results.txt. I have know the relationship between meanscore and footprint from your paper. **But I am curious why some TF may have high meanscore and beautiful footprint tendency while some TF may have not.** Is it means TF with high score is **more importantly** than TF with low, or play more **basicly** function, just like CTCF in your paper (apparent tendency in each timepoint). 
In my opinion, I think it may reflect the true bound in vivo, because if a TF **has many bound** in vivo, it will produce many footprint while **TF with little bound** will be flooded in the nosie and has no apparent tendency.
I also found a correlation in your data
```r
library(tidyverse)
a <- read_delim("~/project/202010/Test_data_TOBIAS_202010/data-tobias-2020/Tcell_bindetect_results.txt",
               delim = "\t")


a %>% 
  mutate(percent = Tcell_day1_footprints_bound / total_tfbs) %>% 
  select(1, Tcell_day1_footprints_mean_score, percent) %>% 
  ggplot(aes(x = Tcell_day1_footprints_mean_score, y = percent)) +
  geom_point()

```

![图片](https://user-images.githubusercontent.com/22555126/97541193-b6d99600-19ff-11eb-9dd7-5ffdb16cc515.png)

Best wishes
Guandong Shang

**Comment by msbentsen** [comment]
Hi Guandong Shang,

Thank you for the comment - an issue for discussion is fine :-)

You are right that many TFs do not produce a clear footprint, while others always do (like CTCF). Some of it probably reflects the number of bound sites in the condition, but there are also TFs which don't show footprints, even when the sites are subset to ChIP-seq verified binding sites. Therefore, the interpretation of `few sites -> more noise -> no footprint` does not always fit. In my opinion, the interpretation is that TFs with high scores are generally found in more open chromatin (but not necessarily showing beautiful footprints). However, these TFs could also be providing "housekeeping" functions, and therefore, it is important to look at the "_change"-columns when comparing between conditions.

With regards to your mean_score vs. percent plot, this relationship is expected. Since the threshold for bound/unbound is set globally, TFs with high scores have a higher chance of being assigned as "bound". Therefore, `high scores -> high mean score -> high percentage bound`.

Best Mette

**Comment by shangguandong1996** [comment]
The causality is interesting:).
By the way, you mentioned 
> the interpretation is that TFs with high scores are generally found in more open chromatin

Is it because TOBIAS try to find the bound site in open chromatin location, so the High score given by TOBIAS will show these TFs bound in more open chromatin?

And I just curious what TFs bound in less open chromatin is? A pioneer TF or A repressive TF?


And thanks again your wonderful reply
Guandong

**Comment by msbentsen** [comment]
> Is it because TOBIAS try to find the bound site in open chromatin location, so the High score given by TOBIAS will show these TFs bound in more open chromatin?

It is because the TOBIAS footprint score is a combined score taking into account both footprintability (e.g. depletion) but also accessibility. As you have also seen yourself, not all TFs leave clear footprints, so the score is more robust towards sparse signals.

> And I just curious what TFs bound in less open chromatin is? A pioneer TF or A repressive TF?

I wish I knew the answer to this question, but I unfortunately don't. If a TF is repressive, the chromatin might close up completely (in which case there would not be any ATAC-seq peak), or the chromatin might be slightly open (in this case, a peak with less signal). But how these observations correlate with the footprint scores of TFs, I don't know. I would say that this requires more information than ATAC-seq alone to uncover.

**Comment by shangguandong1996** [comment]
Thanks Mette, It is a pleasure to talk with you :)
