### ISSUE TITLE
Question - supplying set of pre-defined TFBS sites to BINDetect?

### ISSUE THREAD

**Issue by blairperry** [loosolab/TOBIAS#49]
Hello!

I have a set of TFBS that I have already been using for other analyses that were identified using a different TFBS search tool than is used in BINDetect, but I was hoping to use BINDetect to infer bound/unbound TFs and differential binding metrics using these TFBS sites. I was curious if you had any advice for tweaking the functionality of BINDetect to accept for example a bedfile of TFBS that were already identified? 

Thank you!

BP

**Comment by msbentsen** [comment]
Hi,

There is currently no way to input known TFBS to BINDetect directly. This is because the background needs to be sampled from the same peaks from where the TFBS were found, and this becomes difficult with custom TFBS inputs. But I can share a few ideas for this issue:

- One thing you can do is to tweak the `--motif-pvalue` in such a way that it resembles your known TFBS input - but due to differences in the implementation of motif-scanning, they will probably not be identical.
- You can overlap the result files with your TFBS sites. This won't change the global analysis, but at least you can choose to view the differential binding of single sites specifically for those confirmed by your list. 
- What you might also do is to score your TFBS-inputs yourself using `TOBIAS ScoreBed`. This utility takes a .bed-file as input (e.g. your `known_TFBS.bed`) and scores them with input --bigwigs (e.g. `footprints.bw`), adding columns with the scores. This way, you don't get the BINDetect normalization and bound-threshold, but you can get a sense of up/down relationships by doing a bit of statistics on the columns. 

Sorry that the functionality is not there, but I hope you can use these ideas instead!

Best Mette

**Comment by blairperry** [comment]
Hi Mette,

Thanks for the detailed response! Those ideas are indeed helpful! 

Quick follow-up - my custom TFBS set was generated exclusively for the same peak regions (ATAC-seq peaks) that I am using for BINDetect. As I understand it, the background that is used to calculate the bound-threshold is made by sampling from these entire peak regions, but doesn't take into account specific TFBS positions - is that correct? If so, wouldn't that mean that, as long as my custom TFBS are confined to the same regions from which the background was sampled, the bound-threshold would be the same regardless of the method used to identify TFBS? If that is the case, then it seems like I could use the scoreBed tool to score my custom TFBS and then compare them to the bound-threshold calculated from BINDetect to infer bound/unbound TFs. Would that be reasonable?

Thanks again for your help and for supporting this awesome tool! 

BP

**Comment by msbentsen** [comment]
Yes indeed, if your custom TFBS are found in the same peak-regions as you give to BINDetect, you should be able to use that threshold for your sites! 

I just want to note that splitting into bound/unbound does not necessarily always give you the best view of differential binding, as you can also have sites predicted 'bound' in both conditions, but with high differential scores. That would mean that although a high proportion of cells had a bound TF in condition 1, it might be even higher in condition 2. Calculating differential scores also helps to filter out false-positives which are high-scoring in all conditions. So I would go for the approach of:
1. BINDetect on the known --peaks (with whatever input --motifs you wish, as these won't be used)
2. ScoreBed of custom TFBS against footprint bigwigs
3. Threshold using BINDetect threshold and calculate log2FC on the ScoreBed columns
4. Sort any bound sites by log2FC

**Comment by blairperry** [comment]
Great! Thank you for the information and suggestions! 

Best,
BP
