### ISSUE TITLE
Why choose STAR as a mapping tool?

### ISSUE THREAD

**Issue by linjunhou** [loosolab/TOBIAS#50]
Hi，

I download the test data and repeate the TOBIAS analysis progress for twice.When start with the bam file you provided ,the analysis result as same as you provided but when start with raw data using bowtie2 mapping, the BINDetect result was different with you provided.So I am curious about why you choose STAR as a mapping tool?

Best,
[you_provided_BATF_footprint_comparison_all.pdf](https://github.com/loosolab/TOBIAS/files/5672726/you_provided_BATF_footprint_comparison_all.pdf)
[I_did_BATF_MA1634.1_footprint_comparison_all.pdf](https://github.com/loosolab/TOBIAS/files/5672733/I_did_BATF_MA1634.1_footprint_comparison_all.pdf)

linjun

**Comment by msbentsen** [comment]
Hi linjun,

The choice of mapping tool is purely a personal preference. We have used STAR because it is fast, but the choice of tool should not have massive influence on the results. But of course, different aligners will lead to different read alignments, and thereby silghtly different signal.

For this example, you also have to be aware that the test-data only contains a subset of the genome (in the interest of speed for testing). This is also visible in your plots, where the provided plot contains **990 sites** and the recalculated one contains **3596 sites** (number in the upper right corner of the plots). That might therefore also be a reason for the differing results.

Best Mette

**Comment by linjunhou** [comment]
Mette,

Thanks for your ​reply.

Best Linjun
