### ISSUE TITLE
ATACorrect Stuck on Estimation of Sequence Bias

### ISSUE THREAD

**Issue by bbraun923** [loosolab/TOBIAS#53]
I am running ATACorrect on relatively large ATAC-seq files with >400,000 detected peaks. ATACorrect works well until it reaches 99% for estimation of sequence bias. At that point, it will not complete the command even after several hours. The command works fine for my samples with ~350,000 peaks. Hoping someone maybe be able to assist with the problem?

**Comment by bbraun923** [comment]
Used debug mode to resolve issue.

**Comment by msbentsen** [comment]
Hey @bbraun923,
I'm glad you got it solved, but I am interested in what the problem was? Maybe I can improve something on the logging side. Thanks!

**Comment by bbraun923** [comment]
Thanks for reaching out @msbentsen, 
Essentially, there was a huge pile-up in a non-peak region for some of the samples that caused the estimation of sequence bias to slow-down exponentially. This region should have been blacklisted and TOBIAS worked great after adding the region to my blacklisted bed file. Let me know if you want me to recreate the problem and post here.

**Comment by msbentsen** [comment]
Thank you for the information! You don't have to reproduce - I have had similar problems previously. TOBIAS assumes that the distribution of reads outside of peaks is pretty stable across the chromosomes, but since the non-peak regions are split asynchronously to different cores, it is very hard to foresee these high-signal regions. 

For reference to anyone stumbling across this issue: adding such regions to --blacklist is a good idea 👍 And removing them will not affect estimation of sequence bias in any significant way.

**Comment by lyx-lin** [comment]
Hi, just wondering how to find these non-peak regions?

**Comment by hschult** [comment]
Hi, non-peak regions refer to everything outside the predefined peak regions, which you specify using ATACorrect's `--peaks` parameter.

**Comment by lyx-lin** [comment]
Thank you for the reply and sorry for the confusion! I meant how to find these non-peak regions which may cause the estimation of sequence bias stuck when it reached 99%.

**Comment by hschult** [comment]
You can visually identify them using IGV or if you want to have a file of non-peak regions bedtools is an option.
