### ISSUE TITLE
ATACorrect read depth correction 

### ISSUE THREAD

**Issue by tinakeshav** [loosolab/TOBIAS#54]
Hi, I have a question (novice in atacseq analysis). In ATACorrect, how does <name>_uncorrected.bw correct for depth? (where in the source code much appreciated :) !) 
After converting <name>_uncorrected.bw to bedgraph, I see that some values are floats and not integers, I assume that's because we're correcting for depth? If that's not why, then what's the reason?

**Comment by msbentsen** [comment]
Hi!

The _uncorrected.bw is corrected for depth using a combination of total read count and reads-in-peaks ratio. The correction factor is calculated here:
https://github.com/loosolab/TOBIAS/blob/9d382b2efbd47b4cb0fd29406789fc0664cdc05b/tobias/tools/atacorrect.py#L283-L285

Then, the uncorrected signals are scaled using this factor (correct_factor = bias_obj.correction_factor):
https://github.com/loosolab/TOBIAS/blob/9d382b2efbd47b4cb0fd29406789fc0664cdc05b/tobias/tools/atacorrect_functions.py#L324

Exactly as you mention, because the correction factor is a float, integer read-counts will be scaled into a float space. You can turn this normalization off by using `--norm-off` (correct_factor will be set to 1). I hope this answered your question :-)

**Comment by tinakeshav** [comment]
Thank you so much for your response, you most certainly answered my question.  So --norm-off will simply return number of cut sites for every basepair, correct? 

Though now I'd be grateful for your input on something related. 
After visualizing uncorrected.bw & the pileup bedgraphs produced by MACS, I'm seeing these spikes that I'm having trouble understanding why I see these spikes (bam files were paired end & deduplicated, if it matters). I'd be very happy if I could have your input on why I might be seeing this. 

![image](https://user-images.githubusercontent.com/32367302/105531002-a6f7e800-5cb6-11eb-91d6-e933ee1bbca2.png)

**Comment by msbentsen** [comment]
> 
> 
>  So --norm-off will simply return number of cut sites (with Tn5 offsets taken into account) for every basepair, correct?

Yes, correct! But beware that `_corrected.bw` will still show float-values due to the correction of Tn5-bias.
