### ISSUE TITLE
Question on TOBIAS Bindetect's "overview" file for each transcription factor

### ISSUE THREAD

**Issue by rdbcasillas** [loosolab/TOBIAS#6]
Hello Mette,

We are trying to select the footprints that are most likely to be bound by a TF. TOBIAS's Bindetect produces an "overview" file for each TF which has *score* and *bound* columns for each sample that is being compared.  I want to know how we should understand the relationship between these two columns. 

If the bound column for a sample has lots of zeros for a TF footprint but still gives some score for those footprints, how should we think about that? Should we simply ignore the rows with zeroes for bound column or should we pay more attention to score? Here is an example of what I mean: 

```
KN_score        KN_bound
0.23919 0
0.17    0
0.19418 0
0.05612 0
0.12267 0
0.06019 0
0.08359 0
0.06851 0
0.04142 0
```

If we do remove all the rows with zeroes for bound column, should we then further filter rows with low scores for a particular sample? Or is it a very stringent rule to remove rows with zero bound values and we should instead only focus on score and use a particular threshold for that  in order to filter? 

Thanks a lot, this tool is turning out to be more and more useful for our research! 

Vatsal

**Comment by msbentsen** [comment]
Hi Vatsal,

Great question. The _score column is the footprint score for each condition - higher meaning more likely to be bound (and generally found in more open chromatin). The _bound column signifies the bound/unbound status of each site (0=unbound, 1=bound). As you correctly pointed out, all sites have scores, but only some are predicted to be bound. This split is done by estimating a global threshold across all scores (this threshold is also written to the log of BINDetect with "Threshold estimated at: ..."). So all sites with scores above this threshold are predicted to be bound.

If you have two conditions, I would start by filtering on the _log2fc columns to get the highly changed sites. Next, you can apply some filters to make sure that the sites are bound / scores are above a certain threshold. You might find that the current threshold is too stringent/too loose for you, but it all depends on the downstream application of the data. One of the most important applications of a threshold is to make certain, that high _log2fc scores are not due to small scores (e.g. the problem of log2(1/2) = log2(0.01/0.02)) if that makes sense? 

I am glad that you are finding so much value in TOBIAS!

Best regards,
Mette

**Comment by xiaohanhe2020** [comment]
Hi Mette,
I am using the function of Bindetect. Where can I get my motif file? and also what is the bed file that containg all the peaks? how can I get? I am sorry. I am quit new to coding.

Best wishes
Xiaohan
