### ISSUE TITLE
Recommended handling of replicates

### ISSUE THREAD

**Issue by omansn** [loosolab/TOBIAS#7]
Hello,

Do you have any recommendations for handling replicate data? I have four conditions, each with three replicate experiments. Currently I am running each sample and replicate separately and will use BinDetect to identify common TFBS between replicates. However, since footprinting benefits from read depth, would you recommend merging replicate bams prior to ATACcorrect?

Thank you,
Nathan

**Comment by msbentsen** [comment]
Hi Nathan,

Great question, and yes, I would recommend merging the replicate bams prior to correction and footprinting. The reason for this, as you also mention, is the gain of depth to improve footprinting. Merging the replicates also makes downstream analysis such as visualization of aggregate footprints easier, as you would otherwise have to compare and make sense of 4x3 plots, rather than 4 if you merge the replicates.

Before applying the TOBIAS tools, I would start by clustering all replicates based on a standard count-table of peaks (or your clustering of choice) to see if the replicates are concordant within conditions. If they are, I think you can safely pool and assume that they arose from the same "population". 

Hope this answers your question!

Best Mette
