### ISSUE TITLE
How to interpret the plot output by plotAggregate

### ISSUE THREAD

**Issue by YuZhang337** [loosolab/TOBIAS#71]
I'm trying to get different TF binding between 2 conditions, but get confused by the output plot from plotAggregate.
I get different TF from BINDetect(it shows IRF1 had a higher score in 12merge than 13 merge), then I want to visualize the difference in IRF1 footprint between 2 conditions exclusively for bound sites, but I got confused to interpret it , it print 9 plots and which one is the real comparison of binding scores between 2 conditions ? In my opinion, there is no difference in the two conditions.

here is my command:
TOBIAS PlotAggregate --TFBS ../BINDetect/../IRF1_MA0050.2/beds/IRF1_MA0050.2_12_bound.bed  ../BINDetect/../IRF1_MA0050.2/beds/IRF1_MA0050.2_13_bound.bed   --signals ../ATACorrect/merge2/12merge.last_corrected.bw ../ATACorrect/merge2/13merge.last_corrected.bw --output IRF1_footprint_comparison-subsut2.png --share_y both --plot_boundaries

here is the plot:
![image](https://user-images.githubusercontent.com/70937959/119927996-3ab32b00-bfad-11eb-99aa-d3888ba02e59.png)

Can you give me some advice? Thanks a lot!
Zhangyu

**Comment by msbentsen** [comment]
Hi Zhangyu,

To see the difference between conditions, you might show the "_all.bed"-files instead of the "_bound.bed"-files. This is because the footprints of the bound subset will likely be the same for both conditions (because it is focused on the sites which are bound), but if you view all, you will see the difference in the number of sites. Just looking at the numbers, I would expect that condition "12" will end up showing a bit deeper footprint than condition "13".

It is also possible that there is just not that big a difference between the two conditions. In that case, the interpretation can lie somewhere in "IRF1 binds in both conditions, but a little more in one than the other".

Best Mette

**Comment by YuZhang337** [comment]
Hi Mette,
Thank you very much and sorry for the late reply. I tried it according to your suggestion and it was better.As you said, there is not much difference between them.I need to pick some peaks to do BINdetect.

zhangyu

**Comment by msbentsen** [comment]
Great - I am happy that you figured it out! I will close here, but please reopen in case of more questions.
