### ISSUE TITLE
Error in rule convert_individual_overview running TOBIAS 0.12.10

### ISSUE THREAD

**Issue by Knetsy** [loosolab/TOBIAS#75]
Hi,
I ran TOBIAS in the past and it gave us meaningful results :) ! Now I have a new experiment and I am running TOBIAS 0.12.10 (after running into the issue #64) using the snakemake pipeline and I encountered an error at the rule convert_individual_overview. Looking at the log files it seems to be a problem with R installing packages and the error displayed is : "ERROR: failed to lock directory ...".

I have attached the [log](https://github.com/loosolab/TOBIAS/files/6623373/2021-06-08T141638.707622.snakemake.log) as well as an example of the error message for the transcription factor [SPI1](https://github.com/loosolab/TOBIAS/files/6623384/SPI1_MA0080.5_convert_individual_overview.log) for more clarity.

Thank you in advance for your help!

Deborah

**Comment by msbentsen** [comment]
Hi,

I had a look at this - you are right that something is going wrong with that rule. I think it might be an issue with the initial install of the 'wilson' package. I will see if I can get it solved within the next couple of days.

If you don't need those files, you can also tell snakemake to just keep going even if some rules fail. This is done by appending `--keep-going` to the snakemake call on the commandline. This will ensure that all other rules finish as planned. Hope you can use this as a temporary solution.

Best Mette

**Comment by msbentsen** [comment]
I just made some updates to the snakemake [respository](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake), which should solve the issue. I split some of the packages into individual conda environments, so the first run of the pipeline might take a little longer due to building the new environments. Also, if you use the same output folder, please delete the "wilson" folder before re-running the pipeline - that will ensure that wilson is re-installed (this time correctly). 

Please let me know if this solves the issue, thanks!
