### ISSUE TITLE
Is it possible to change settings in PlotAggregate?

### ISSUE THREAD

**Issue by sopenaml** [loosolab/TOBIAS#76]
Is it possible to change settings in the output of PlotAggregate? as change colors on profiles, remove legend or grey background on plot  combining more than one sample?

**Comment by msbentsen** [comment]
No, unfortunately there is currently no way to change those settings. What I can recommend you do is to output the plot in .pdf-format, and open it in any vector graphics editor such as Inkscape. There, all the elements of the graph (legends, footprint profiles, backgrounds etc.) are available as individual objects, and with a bit of hacking, you can change the colors/remove objects post-plotting. 

Otherwise, I will also happily take any pull requests for adding new functionality to PlotAggregate! :-)
