### ISSUE TITLE
TOBIAS for single end libraries? 

### ISSUE THREAD

**Issue by NatashaJansz** [loosolab/TOBIAS#84]
Hello Mette,
I was hoping to use ATACorrect on single-end ATAC-seq data. Is this possible, or will it only work with paired end data?

I tried to run the command and got the below error:
`TOBIAS: error: unrecognized arguments: —-bam ../bamfiles/ATAC_HeLa_SE_primed_24h.bam`

Thank you very much!
Natasha

**Comment by msbentsen** [comment]
Hi Natasha,

It seems that the issue lies in the `—-bam` statement - it looks like one dash is a long dash. Therefore, the argument is not being recognized. So the error has nothing to do with paired-end/single-end, and TOBIAS should work with both types of data. Let me know if replacing `—-bam` with `--bam` solves the issue, thanks!

Best Mette

**Comment by NatashaJansz** [comment]
Hi Mette,
Thank you for such a quick reply! Great that it woks with both paired and single end reads. 
Fixing the -- did work, thanks for spotting that. Formatting error from copy and paste from text edit.
Thanks again! Natasha
