### ISSUE TITLE
Normalisation of binding scores across conditions

### ISSUE THREAD

**Issue by liz-is** [loosolab/TOBIAS#87]
Hello,

I've run TOBIAS on different cell clusters (along a developmental trajectory) from a scATAC-seq experiment, and I wanted to plot the binding scores of some TFs of interest across all cell clusters as a heatmap (below). I realised that the binding scores are globally lower for clusters 10 and 11. 

![image](https://user-images.githubusercontent.com/3035709/127676923-322b69fb-14cb-45ee-90fc-edf4f6126980.png)

I had a look at some previous issues and saw that you use quantile normalisation to normalise binding scores across conditions before assessing differential binding (if I understood correctly). Are these normalised scores written to the output `bindetect_results.txt` file? If not, do you think it would make sense to apply quantile normalisation across the mean scores before making the heatmap?

I'm not really sure why these two clusters would be problematic - they do have fewer cells (and therefore lower coverage) than the others, but not by a huge margin. If you have any suggestions about where to start to debug the reasons these datasets look different, I'd be happy to hear them!

**Comment by msbentsen** [comment]
Hi @liz-is,

Sorry for the delay in answer - holidays and other projects got in the way.

Yes, you are correct that BINDetect uses quantile normalization, and these are written out in the bindetect_results.txt file (the scores in the `<condition>_mean_score` columns are normalized). There are also some visualizations of the distributions before/after normalization within the `bindetect_figures.pdf`-file, which you might have a look at.

Are you using the same `--peaks`/`--regions` input for all of the preprocessing of the data? Even when doing bias correction and footprinting, you want to make sure that the peaks are covering all conditions in order to compare between them. 

I also sometimes see these differences in "quality" that cannot really be explained. Might be differences in the digestion by Tn5 (can be seen in an insert-size-distribution-plot) or might be reads-in-peaks ratio showing different noise levels. In the end, if you trust the data, you might also say "Hmm okay, BINDetect did for some reason not normalize these correctly, but I know they are similar, so I will perform my own additional step of normalization". What you can also do is to normalize across both the columns and rows to see changes in TF binding between the clusters. The heatmap currently highlights that some TFs always have high scores, and some always have low - but there might still be changes across clusters for low-scoring TFs. This all depends on the questions you have in mind of course.

I hope this was helpful!

**Comment by liz-is** [comment]
No worries!

Yes, I'm using the same set of peaks for all preprocessing steps and all samples. Good to know that this is the quantile-normalised values already. 

I did have a look at the plots and also ran TOBIAS with `--debug` to see if the additional plots gave any insight. These two clusters have more zero scores, both before and after normalisation, and the quantile-quantile plot also shows a different relationship. I don't really know what to to with this information but I'm including the plots here in case they are useful to you in any way! 

![Screenshot 2021-08-17 at 09 34 04](https://user-images.githubusercontent.com/3035709/129684277-1cd4e46e-74c1-4590-9126-4aa8ecb7ed65.png)
![Screenshot 2021-08-17 at 09 34 51](https://user-images.githubusercontent.com/3035709/129684286-15af1680-62f8-4c5d-b783-cb5ed2fa5ea5.png)

The increase in zero scores does also match other QC I've done - these clusters have fewer peaks with signal in them (insert size distribution, overall fraction of reads in peaks, TSS enrichment, etc, are all similar between these clusters and others). And I've now done other analyses on this data like nucleosome positioning, where these clusters also had different results from all of the others. So, I guess this is not a TOBIAS-specific thing and rather some underlying issue with the data that needs further investigation before I can decide if I trust the data.

Thanks for your input and the useful tool! :)
