### ISSUE TITLE
Question about CreateNetwork

### ISSUE THREAD

**Issue by DittmanC** [loosolab/TOBIAS#89]
While I am trying step by step to process my ATAC Seq data, I am stuck in the step of CreateNetwork.
The ouput file I got are lists of {motif}_path_edges.txt and {motif}_paths.txt, may I know how to create a network diagram to illustrate the TF interaction? or Does it requires another software to generate?
Thanks a lot!

**Comment by msbentsen** [comment]
Hi,

Yes, you will need an external software to create the diagram, as CreateNetwork only writes out the edge-table in .txt format. I can recommend something like Cytoscape (https://cytoscape.org/), but you can use your software of choice.

You can either use the global `edges.txt` file containing all factors (also contains more information), or the individual networks for each TF (`<TF>_path_edges.txt`). Within Cytoscape, you can load the network using: "File" -> "Import" -> "Network from file" and set the appropriate Source and Target nodes. You can then use Cytoscape to visualize the network with different layouts. 

Hope that helps you out!

**Comment by DittmanC** [comment]
from the result of CreatNetwork, each individual of ${TF}_path_edges.txt was generated. When I open each of them, it contains "Source"	"Target"	and "Level". Is it common to have only level 2? 
Basically, I use TOBAIS CreatNetwork --TFBS ${condition}_BINDetect/${TF}/beds/${TF}_${condition}_bound.bed and the --origin I grep all my annotated gene and corresponding geneID to create a motif2gene.txt file 
am I doing something wrong?

**Comment by msbentsen** [comment]
The number of levels will depend a lot on the data. The example data finds very few paths because it is limited to one chromosome, so it always depends on how many sites could be annotated to genes.

I think your approach sounds right! So you are running `TOBIAS CreateNetwork` with all the TFBS in one run, right? So basically `--TFBS <bindetect_folder>/*/beds/*_<condition>_bound.bed`. The run will also write out some statistics on how many sites had matching ids - this might tell you if the motif2gene.txt file was correct.

You are also welcome to send me some of the files if you are still in doubt :slightly_smiling_face:
