### ISSUE TITLE
Low mean scores after BINDetect

### ISSUE THREAD

**Issue by jh-rocha** [loosolab/TOBIAS#92]
Hi.

I’d like some help with footprinting analysis. I looked for footprinting methods using ATAC-seq data and looks that TOBIAS is a really good one, so I used ATACorrect, FooutprintScores and BINDetect using the test data you provide and everything looks OK. When I run the same tools with my own data, the bindetect_results.xlsx file shows very low mean scores (mean score < 2 for every TF).

This is the first time I work with TOBIAS so I have no idea if this is an issue or maybe a interpretation problem?. Really hope you can give me some insights on how to deal with this.

Thanks. 

Below are the log files.

[ATACorrect.out.txt](https://github.com/loosolab/TOBIAS/files/7158012/ATACorrect.out.txt)
[FootprintScores.out.txt](https://github.com/loosolab/TOBIAS/files/7158024/FootprintScores.out.txt)
[BINDetect.out.txt](https://github.com/loosolab/TOBIAS/files/7158026/BINDetect.out.txt)

**Comment by msbentsen** [comment]
Hi, 

Thank you for this issue! The scores are always relative to the dataset used, also because they are normalized to the library depth and reads-in-peaks-ratio of the specific sample. This can also be seen in the ATACorrect log:
```
2021-09-10 16:47:39 (26161) [STATS]	LIB_NORM	0.08123
2021-09-10 16:47:39 (26161) [STATS]	FRiP	0.62740
2021-09-10 16:47:39 (26161) [STATS]	CORRECTION_FACTOR:	0.12948
```

So it is generally not a problem if the mean scores are lower/higher - they are relative and cannot be compared across different runs. How do the results look otherwise? That might be a better indicator of whether something failed.

**Comment by jh-rocha** [comment]
Hi,

Here is the file that I got after running BINDetect.
[bindetect_results.xlsx](https://github.com/loosolab/TOBIAS/files/7166141/bindetect_results.xlsx)

I have a few more questions.
1.- Is there any threshold that you can suggest to say a TF has a good footprint?.
2.- What's the desired sequencing depth ( or number of reads mapped to the genome) that a sample should have to get decent results using TOBIAS?.
3.- Any other consideration I should take into account to perform a good footprinting analysis using TOBIAS?.

Thanks so much.

**Comment by msbentsen** [comment]
Hi, 

1. The thing with the score is, that it is composed of both accessibility of the site, and the evidence of footprint. Therefore, you might have a high score due to accessibility, even if you cannot see a footprint. So setting a threshold by score is not possible, but you might have a look at the output of `TOBIAS PlotAggregate` to see whether a footprint is visible or not.

2. I usually reference the ENCODE guidelines here: https://www.encodeproject.org/atac-seq/#standards, which state 25 million non-duplicate non-mitochondrial fragments. The most important thing is to have a good signal-to-noise ratio, as you essentially only want reads in the regions of interest for footprinting (the peaks). Also, a plot of fragment size distribution might be helpful to see whether the sample was appropriately digested by Tn5 - so not too much or too little.

3. You have to take in mind that not all TFs create nice footprints, so take the footprint shapes with a grain of salt :-) Also, some TFs generally have higher scores than others, so doing a differential analysis (e.g. control vs. another condition) will help to highlight not only high-scoring TFs, but highly changeable TFs. If you have that data available, I will highly recommend running BINDetect with two conditions.

Best regards,
Mette
