### ISSUE TITLE
Footprinting for multiple tissues.

### ISSUE THREAD

**Issue by tzhu-bio** [loosolab/TOBIAS#98]
Thanks for your TOBIAS.

Now I have multiple tissues (>15), I want to compare them with footprinting. Is TOBIAS capable of doing such an analysis? Can you give me some advice?

**Comment by tzhu-bio** [comment]
> Thanks for your reply.
Do you mean that the sample_footprints_mean_score of each sample is extracted in **bindetect_results.txt**? 
I took this information to construct a matrix of n_TF x n_footprint_score, but the difference between these scores is too small to compare the differences between different tissues.

**Comment by msbentsen** [comment]
Yes, I mean **bindetect_results.txt**. In order to compare the scores, you might have to normalize each row with e.g. Z-score. Otherwise, you will have a bias in the TFs with generally high footprint scores, and those with generally low footprint scores. So maybe that is why the scores seem so low. 

But since the statistics behind TOBIAS are different, I cannot promise that it will turn out the same way as the original plot.
